### ISSUE TITLE
add toContainQuerySelector matcher for better errors

### ISSUE THREAD

**Issue by davidje13** [testing-library/jest-dom#106]
### Describe the feature you'd like:

Currently the recommendation for checking if an element exists is:

> ```javascript
> const htmlElement = document.querySelector('[data-testid="html-element"]')
> const nonExistantElement = document.querySelector('does-not-exist')
> 
> expect(htmlElement).toBeInTheDocument()
> expect(nonExistantElement).not.toBeInTheDocument()
> ```
(abridged from the docs)

But this returns pretty useless errors if the condition is not met. It would be much more useful to combine the `querySelector` with the existence check, such as:

```javascript
expect(document).toContainQuerySelector('[data-testid="html-element"]')
expect(document).not.toContainQuerySelector('does-not-exist')
```

(this is also much shorter syntax)

This is comparable to `toContainMatchingElement` from the `enzyme-matchers` project.

### Suggested implementation:

I've tried to match the code style of this project, but might have missed something:

```javascript
import {matcherHint, printReceived, printExpected} from 'jest-matcher-utils'
import {checkHtmlElement} from './utils'

export function toContainQuerySelector(element, selector) {
  checkHtmlElement(element, toContainQuerySelector, this)
  return {
    pass: Boolean(element.querySelector(selector)),
    message: () => [
      matcherHint(`${this.isNot ? '.not' : ''}.toContainQuerySelector`, 'element', 'selector'),
      '',
      `Expected ${this.isNot ? 'no elements' : 'an element'} matching`,
      `  ${printExpected(selector)}`,
      'Received',
      `  ${printReceived(element)}`,
    ].join('\n'),
  }
}
```

### Describe alternatives you've considered:

- `.not.toBe(null)` or a hypothetical `.toExist()`, etc. have similar problems to `.toBeInTheDocument`: the returned error is not helpful for diagnosis because it does not include the content which was actually observed when an element is missing.

- It might be valuable to be able to count the number of occurrences (e.g. `toContainQuerySelector('foo', 4)` to check for exactly 4 occurrences, but I can't think of a self-descriptive method name for this, so as-proposed this checks for 1-or-more, or exactly zero.

### Teachability, Documentation, Adoption, Migration Strategy:

Recommendation can be updated to:

```javascript
expect(document).toContainQuerySelector('[data-testid="html-element"]')
expect(document).not.toContainQuerySelector('does-not-exist')
```

No migration necessary; existing matchers do not need to change.

**Comment by gnapse** [comment]
Hi, I've been thinking about this, that's the reason for the delayed response. Sorry about that.

I'm hesitant of providing this. The argument for the unhelpful error message when `toBeInTheDocument` seems compelling, but don't you get also the line of the failed `expect`?

On the other hand, the downside is that this custom matcher feels to move away from the testing libraries' [guiding principle](https://twitter.com/kentcdodds/status/977018512689455106). It encourages testing the internal markup structure rather than encouraging asserting based more on what the user sees. Granted you can still do it today via `document.querySelector` and `toBeInTheDocument`, but the more declarative custom matchers do not promote this way of doing things.

That being said, I'm open to hear a stronger case for this. Or maybe the input from @kentcdodds and @alexkrolick would be nice.

**Comment by davidje13** [comment]
For me the problem is more around knowing what was actually rendered, not about what element was not found.

For example, suppose I have a list element with an empty state. I expect to see the empty state, but I don't, so the test fails. OK, so I can infer that it didn't render the empty state, but I have no idea why without digging in to code. If instead it said "failed to find 'my-empty-state' in <ul><li>global</li></ul>" then I can say "d'oh, I forgot that it will always contain 'global'; my empty state check needs to apply if the list contains only one item" (silly example).

As you say, the existing error for the negated version is pretty OK already. It's just the non-negated version which is bad.

I'm very uneasy about the naked `getByTestId('html-element')`. That doesn't read well as code, because there is no hint that an assertion is being made; it just looks like some code left behind by mistake. And in a similar vein, using `toBeInTheDocument` as a no-op to hide this seems hacky (and it implies that you could negate it with `.not.`, but that won't actually work). The "correct" test would be the rather horrendous:

```javascript
expect(() => getByTestId('html-element')).not.toThrow(); // err...

// negated: ("expect not to be in the document")
expect(() => getByTestId('html-element')).toThrow(); // what? what is this?!
```

I understand the concern around using native query selectors rather than the helpers. I quite like selenium's `By` approach for this, which could be translated to:

```javascript
expect(document).toContainElement(By.testId('html-element'));
expect(document).toContainElement(By.querySelector('.whatever'));
expect(document).toContainElement(By.name('password'));
// etc.
```

**Comment by davidje13** [comment]
You could even try something crazy like this:

```javascript
expect(getByTestId).toFind('html-element');
expect(getByTestId).not.toFind('html-element');

expect(document.querySelector).toFind('.whatever');
expect(document.querySelector).not.toFind('.whatever');
```

Where the `toFind` matcher takes in a function, invokes it with the arguments given at the end, and checks that the result is a HTMLElement. If it is not (or if it throws), it can provide an error message which includes the current DOM structure to aid debugging. It would never throw; by failing instead it will always be possible to negate it in a meaningful way.

**Comment by alexkrolick** [comment]
> And in a similar vein, using toBeInTheDocument as a no-op to hide this seems hacky (and it implies that you could negate it with .not., but that won't actually work). The "correct" test would be the rather horrendous:
> 
> `expect(() => getByTestId('html-element')).not.toThrow(); // err...`
>
> `expect(() => getByTestId('html-element')).toThrow(); // what? what is this?!`

Why not this:

```js
expect(queryByTestId('html-element')).not.toBeInTheDocument()
```

`queryBy*` doesn't throw and the assertion should print the DOM

**Comment by davidje13** [comment]
@alexkrolick true, but the reverse:

```javascript
expect(queryByTestId('html-element')).toBeInTheDocument()
```

produces a bad error message if it fails, which is what @kentcdodds was suggesting `getByTestId` for (since the thrown error in that case is actually helpful).

If you think it should be a helpful error, maybe that means this is actually a bug in `toBeInTheDocument`? What it shows now is this:

> ```
> received value must be an HTMLElement or an SVGElement.
>     Received has value: null
> ```

Which is totally useless.

Overall, it means the current state is rather inconsistent / incomplete:

```javascript
expect(getByTestId('html-element')).toBeInTheDocument() // works, good error message on failure, but throws rather than failing and the matcher is only present for appearances sake
expect(getByTestId('html-element')).not.toBeInTheDocument() // never works (either fails or throws)

expect(queryByTestId('html-element')).toBeInTheDocument() // works, and does not throw, but (very) bad error message on failure
expect(queryByTestId('html-element')).not.toBeInTheDocument() // works, and does not throw, with a reasonable-enough error message on failure
```

**Comment by alexkrolick** [comment]
I think we could safely remove the `||` here and allow it to return `false` and print the full error here: 

https://github.com/testing-library/jest-dom/blob/b2b4bd3ba65c48b350194a7623797e70f8a1390e/src/to-be-in-the-document.js#L9-L11

**Comment by gnapse** [comment]
First, about these two uses:

```js
expect(getByTestId('html-element')).toBeInTheDocument()
expect(getByTestId('html-element')).not.toBeInTheDocument()
```

Combining `getBy*` with `toBeInTheDocument` does not make sense. `getBy*` helpers are already meant to raise an error and make your test fail if the element is not found.

Now, on to the other part:

```js
expect(queryByTestId('html-element')).toBeInTheDocument()
expect(queryByTestId('html-element')).not.toBeInTheDocument()
```

I understand your point, but there's hardly something we can do with `toBeInTheDocument` when used in that way. If `queryByTestId` returns `null`, `toBeInTheDocument` can hardly do anything at all. It received `null` instead of an element, so it cannot render any context in the markup to help you.

@alexkrolick's suggestion might help, but I suspect the error message if we let this go through at that point in the code would not be helpful either. Think about it, the matcher was called with `element: null`. It has nothing to print. Unless it prints out the entire document, so you can see that what you were looking for is not in there (but that's what the matcher's failure is already telling you).

**Comment by alexkrolick** [comment]
>  so you can see that what you were looking for is not in there (but that's what the matcher's failure is already telling you).

That's the suggestion, in the same way that getBy prints the DOM when it fails. It helps diagnose the issues much faster than adding debug/prettydom calls.

**Comment by gnapse** [comment]
Seems like the consensus here was to not add the proposed feature. I'll be closing this for the time being.
