### ISSUE TITLE
Add toBeChecked for <input type="radio" /> and <input type="checkbox" />

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/jest-dom#107]
### Describe the feature you'd like:

I want this to work:

```javascript
const input = document.createElement('input')
input.setAttribute('type', 'checkbox')
input.setAttribute('checked', true)
expect(input).toBeChecked()
input.setAttribute('checked', false)
expect(input).not.toBeChecked()
```

### Describe alternatives you've considered:

```javascript
expect(input.checked).toBeTrue()
```

### Teachability, Documentation, Adoption, Migration Strategy:

This would need to be added to the docs like the rest of the assertions.

**Comment by lourenci** [comment]
It would be nice. Will you handle this?

**Comment by kentcdodds** [comment]
As much as I'd love to do it myself, I don't know if I have the bandwidth at the moment. Just wanted to toss it in as an idea :)

**Comment by lourenci** [comment]
I could handle this. :)

**Comment by gnapse** [comment]
Hmmm, although I like the descriptiveness of this, this kinda messes up with the additional guiding principle of `jest-dom`:

> this library aims to maintain a minimal but useful set of them, while avoiding bloating itself with merely convenient ones that can be easily achieved with other APIs. In general, the overall criteria for what is considered a useful custom matcher to add to this library, is that doing the equivalent assertion on our own makes the test code more verbose, less clear in its intent, and/or harder to read.

It could be argued that this is easier to read though.

However, wouldn't this work?

```js
expect(input).toHaveAttribute('checked', true)
```

**Comment by kentcdodds** [comment]
Fair point 👍 I'm convinced.

**Comment by gnapse** [comment]
@kentcdodds but because of the guiding principle? Or because the line I suggested works?

**Comment by kentcdodds** [comment]
Both 👍 because what you different works there's not enough justification to add to the surface area of the assertion library

**Comment by Belco90** [comment]
I almost opened the same issue but I found this one, so leaving a comment here. I also found `toBeChecked` assert really interesting and I'm not sure if `.toHaveAttribute('checked', true)` covers all the cases.

I rewrote @kentcdodds tests in 2 different ways:
```
describe('input checkbox', () => {
  it('should handle attribute checked', () => {
    const input = document.createElement('input');
    input.setAttribute('type', 'checkbox');
    input.setAttribute('checked', true);
    expect(input).toHaveAttribute('checked', 'true');
    input.setAttribute('checked', false);
    expect(input).toHaveAttribute('checked', 'false');
  });

  it('should handle property checked', () => {
    const input = document.createElement('input');
    input.setAttribute('type', 'checkbox');
    input.checked = true;
    expect(input).toHaveAttribute('checked', 'true');
    input.checked = false;
    expect(input).toHaveAttribute('checked', 'false');
  });
});
```

The first one pass but the second one doesn't as it needs to check that `input.checked === true`. I don't know if `toHaveAttribute` was covering this case before and it doesn't now, or if I'm missing something else. Would make sense now to add `toBeChecked` assertion?

Thanks.

**Comment by kentcdodds** [comment]
I agree with that logic. Makes plenty of sense to me

**Comment by gnapse** [comment]
Yes, it makes sense, although now I wonder what really makes a checkbox be checked? Is it the attribute or the `.checked` value? (a quick smoke test in my browser console seems to suggest the `.checked` property is the one that's taken into account). However, when I set the attribute to `true` for a new checkbox, the `.checked` property turned true, but when I set the attribute to `false`, the `.checked` property remained `true` 🤔

And to make matters worse, there's also `.indeterminate` ([ref](https://css-tricks.com/indeterminate-checkboxes/), [ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Indeterminate_state_checkboxes)). Does that mean we should add `.toBeIndeterminate()`?

I still think that, although a bit less declarative, if we add a `.toBeChecked()` that is simply a replacement for writing `expect(checkboxElement.checked).toBe(true)` is not worth it. What comes next? `.toBeUnchecked()`?

However, if we figure out all the needs around checking a checkbox state (the ambiguity between the state of the `checked=` attribute and the `.checked` DOM property) and maybe also bring `.indeterminate` into the mix, and provide a custom matcher that would hide away all the complexity of checking a checkbox state, I'd me more willing to consider it.

That being said, of course I don't mean to say that mine is the last word. Just my 2 cents. If this is just a replacement for `expect(checkbox.checked).toBe(true)` for me is not worth it, and would love to hear if for others it is.

**Comment by kentcdodds** [comment]
Wouldn't need `toBeUnchecked()` because you can do `.not.toBeChecked()` 🤷‍♂️

**Comment by kentcdodds** [comment]
Also, I don't think that we need to support things that a tiny fraction of people would use "just for completeness." I hadn't even heard of the `.indeterminate` state before today. 🙃

**Comment by gnapse** [comment]
> Wouldn't need toBeUnchecked() because you can do .not.toBeChecked()

Yes, I removed that after my initial comment posting because it was not fair.

You still haven't addressed my main question (on which I am honestly not fully decided): do you think it's worth it to have a custom matcher that simply replaces a check for a value being `true`? A value that's readily available?

**Comment by kentcdodds** [comment]
Yes I do. Because the code is more communicative and the error message would be more helpful 👍

**Comment by Belco90** [comment]
> I agree with that logic. Makes plenty of sense to me

@kentcddods Absolutely, but I think it proves `toBeChecked` matcher is worth to be added.

@gnapse If you finally decide to implement the matcher, I'm happy to help.

**Comment by gnapse** [comment]
@Belco90 Like I said before, it's not for me to decide wether we add it or not, but what turns out of the discussion here. It seems we're leaning towards it, what Kent and others have said make sense (although I still think it's kinda a syntactic sugar, but ok). If you mean you're up to providing a PR, please do so.

**Comment by gnapse** [comment]
Actually, I have thought of an extra functionality that this custom matcher may have that could make it more useful: it could check also for [`aria-checked`](https://www.digitala11y.com/aria-checked-state/).

More concretely, it should check either that

1. The element is a `input` of type `checkbox` or `radio` and in that case it should use the `.checked` property to determine if it passes or not.
2. The element has a `role` of `checkbox`, `option`, `radio` or `switch`, and in that case it should use the `aria-checked` attribute to decide if it passes or not.

Not sure what should it do if the element is none of the above cases. Maybe also fail with a different message?

**Comment by kentcdodds** [comment]
Love that suggestion!

**Comment by weyert** [comment]
Brilliant!

**Comment by afontcu** [comment]
I feel this is a nice addition to the library 👍 


> Maybe also fail with a different message?

What about pointing out that the element check property cannot be asserted due to missing right `role` and `type` attributes?

A question that comes to my mind, though, is how far should `jest-dom` should go in terms of accessibility. For instance, a "fake" checkbox such as `<div role="checkbox" aria-checked="false">` would require a `tabindex` attribute, too. I guess this is not the right issue to discuss that, but it's quite related the minute we add ARIA attributes to the mix.

**Comment by kentcdodds** [comment]
I definitely see this as an opportunity for us to help people if they decide they want to write a custom checkbox 👍

**Comment by gnapse** [comment]
I agree, however, with a caveat:

The thing is, that's a bit tricky. Because in not all situations the thing with `aria-checked` should be focusable. For example, a `<div role="option" />` need not be focusable, and be part of a combobox where the input keeps focus, and uses `aria-activedescendant` to declare what option in the combobox listbox is the one "focused" right now.

All I'm saying is, this, if done, has to be done right and checking out the spec. Not blindly assuming that a div with a `role` has to have a `tabindex`.

**Comment by kentcdodds** [comment]
I suggest that we get a simple implementation released first, then we add the aria support later

**Comment by Belco90** [comment]
If this `toBeChecked` is finally implemented, should affect others matchers like `toHaveFormValues`?

**Comment by kentcdodds** [comment]
I don't see why it would need any changes
