### ISSUE TITLE
Scoped package?

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/jest-dom#115]
No pressure. I'm just wondering whether you've thought about moving to the scoped package format like the rest of the testing-library family of tools.

**Comment by gnapse** [comment]
Yes, haven't had the time. Will look into it.

**Comment by kentcdodds** [comment]
Ping. Would you like me to do this?

**Comment by gnapse** [comment]
Yes, please. Thanks @kentcdodds. I'm not too confident on this packaging and publishing things, and was worried that I may break it if done in a hurry.

**Comment by kentcdodds** [comment]
Alright! This is done 💯
