### ISSUE TITLE
<select> element value change is not recognized properly by toHaveFormValues

### ISSUE THREAD

**Issue by gnapse** [testing-library/jest-dom#117]
* `jest-dom` version: 3.5.0

### Relevant code or config:

```js
const { container } = render(
  <form>
    <select name="priority">
      <option value="low">Low</option>
      <option value="medium">Medium</option>
      <option value="high">High</option>
    </select>
  </form>
)
const form = container.querySelector('form')
const select = container.querySelector('select')
fireEvent.change(select, { target: { value: 'high' } })
expect(form).toHaveFormValues({ priority: 'high' }) // <- fails here
```

The above test should pass, but it does not. It fails to recognize the change in the selected value of the `select`.

### Problem description:

After some digging I'm pretty sure this has something to do with the cause of [this issue in dom-testing-library](https://github.com/testing-library/dom-testing-library/issues/115). This issue was fixed in [this PR](https://github.com/testing-library/dom-testing-library/issues/124), and this is mention in that PR description:

> Since `selectedOptions` is not a reactive property, JSDOM was not updating to match the selected option in a select Element. The selected attribute is reactive.

We're using `selectedOptions` ourselves to check the selected options in a `select`. See [the relevant code](https://github.com/testing-library/jest-dom/blob/fd747bf470433e72d34be78e169fb213e0284e8f/src/utils.js#L141-L150).

### Suggested solution:

Maybe following the same approach as testing-library/dom-testing-library#124 and switch to use the `select` attribute instead.

**Comment by jeanchung** [comment]
Hi! I just made a PR to fix this issue. ^

**Comment by weyert** [comment]
Thank you, you rock :D
