### ISSUE TITLE
Is there a migration guide for old jest-dom ?

### ISSUE THREAD

**Issue by DavidBabel** [testing-library/jest-dom#119]
Sorry but yet, if i just switch from jest-dom to @testing-library/jest-dom nothing behave as expected.

My guess is that Jest may not manage it yet, but i did not find any migration helper. Is there one ?

**Comment by afontcu** [comment]
Hi @DavidBabel, what issues did you encounter? Did you try removing the package altogether and installing it again? if still failing, what versions of `node` and `npm` are you using?

There's no "migration guide" because nothing really changed.

**Comment by gnapse** [comment]
I believe a complete list of steps looks like this:

1. Replace the library package

```shell
npm uninstall jest-dom && npm install @testing-library/jest-dom --save-dev
```

> Adjust for `yarn` accordingly

2. Replace the source package in all relevant imports

```diff
-import 'jest-dom/extend-expect';
+import '@testing-library/jest-dom/extend-expect';
```

@DavidBabel Let me know if this is what you did and if you're still having trouble.

**Comment by gnapse** [comment]
I'm going to close this. Feel free to re-open or comment if there's still something not clear or not working as expected.
