### ISSUE TITLE
How to use this library with VSCode autocomplite?

### ISSUE THREAD

**Issue by antonpegov** [testing-library/jest-dom#160]
I using react with typescript and everything work fine except I can't setup my vscode autocomplete to use this methods.

**Comment by gnapse** [comment]
Most probably related to #123

**Comment by GideonZhao** [comment]
Could anyone please help with this? I'm facing the same issue here. I used a simple app to test this, here is the "package.json":

`{
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "@testing-library/dom": "^8.20.0",
    "@testing-library/jest-dom": "^5.16.5",
    "jest": "^29.4.2",
    "jest-environment-jsdom": "^29.4.2"
  }
}`

However, the VSCode doesn't resolve any jest-dom matchers:
![image](https://user-images.githubusercontent.com/30718987/218009762-6c6f368d-3e23-49dd-90ba-1754268654fd.png)

**Comment by Jahmilli** [comment]
@GideonZhao  did you import the type package? As suggested in the related issue, just do `npm i -D @types/testing-library__jest-dom` (or Yarn, pnpm equivalent for installing dev packages) and you should be able to see the types :)

**Comment by GideonZhao** [comment]
> @GideonZhao did you import the type package? As suggested in the related issue, just do `npm i -D @types/testing-library__jest-dom` (or Yarn, pnpm equivalent for installing dev packages) and you should be able to see the types :)

Hi @Jahmilli Sorry, I didn't look at the previous comments carefully. After importing the type package, I still cannot see the "toHaveClass" in autocomplete.

package.json:
`{
  "dependencies": {
    "@testing-library/dom": "^9.0.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@types/testing-library__jest-dom": "^5.14.5",
    "jest": "^29.4.3",
    "jest-environment-jsdom": "^29.4.3"
  }
}
`
code:
![image](https://user-images.githubusercontent.com/30718987/220035247-78a443be-4541-4bc5-ba79-df19e94bd4dd.png)
