### ISSUE TITLE
Tests in VS Code throw TypeErrors

### ISSUE THREAD

**Issue by pjaws** [testing-library/jest-dom#167]
- `react-testing-library` version: 9.3.2
- `react` version: 16.11.0
- `node` version: 12.6.0
- `npm` (or `yarn`) version: 6.13.1

### Relevant code or config:

```js
// Sample.js
import React from 'react';

function Sample() {
  return <div>Sample</div>;
}

export default Sample;

// Sample.spec.js
import React from 'react';
import { render } from '../test-utils';
import Sample from './Sample';

describe('Sample', () => {
  it('renders without crashing', () => {
    const text = 'Sample';
    const { getByText } = render(<Sample />);

    expect(getByText(text)).toBeInTheDocument(); // TypeError: expect(...).toBeInTheDocument is not a function
  });
});
```

### Problem description:

I have the `vscode-jest` extension installed to automatically run tests inside VS Code, and all of the queries provided by Testing Library throw the following error: `TypeError: expect(...).toBeInTheDocument is not a function`.

The tests pass when I run them in the terminal, but obviously, it's pretty annoying to have all my test files showing "red" inside my editor.

I don't know if this is an issue with the Jest extension, Testing Library, or some combination of the two, but I have to imagine other people have run into this and solved it, though I couldn't find an answer to this by searching.

Any help is greatly appreciated!

**Comment by JPBlancoDB** [comment]
Hi @pjaws, you need to install jest-dom `npm install --save-dev @testing-library/jest-dom` and then import it into your config file if you want to have those available globally:
`import '@testing-library/jest-dom/extend-expect'
or you could add it into your test 
`import {toBeInTheDocument, toHaveClass} from '@testing-library/jest-dom'`

**Comment by pjaws** [comment]
I already have it installed, along with the setup file...

**Comment by JPBlancoDB** [comment]
Could you share your setup file?

**Comment by gnapse** [comment]
> Could you share your setup file?

Or a minimal repo where the issue can be reproduced?

**Comment by pjaws** [comment]
As I was setting up the example repo, I re-opened the existing project I was having issues with to copy code, and it seems that reloading VS Code solved this issue for me. Hopefully if anyone else runs into this, it will be the solution for them as well.

Probably safe to close this issue.

**Comment by misolo** [comment]
I have the same issue
run `npm run test`, get error `TypeError: expect(...).toBeInTheDocument is not a function`  
I've tried everything: re-opened vs code/ restart / rm -rf node_modules; npm install but it still fails
```  
 "@testing-library/jest-dom": "^4.2.4",
 "@testing-library/react": "^9.5.0",
 "jest": "24.9.0",
```
any idea?

**Comment by gnapse** [comment]
@misolo your tests run ok when run directly in the terminal, and only fail in this way when run in vscode's terminal or by vscode's jest extension?

**Comment by misolo** [comment]
It finally works after I upgraded the latest:
```
   "@testing-library/jest-dom": "^5.5.0",
   "@testing-library/react": "^10.0.3",
```

**Comment by kentr** [comment]
For me, this worked:

1. Change the VS Code *Path to Jest* setting for the workspace to `npm run test --`
2. Restart the Jest runner in VS Code.

**Comment by paccao** [comment]
Sorry for commenting on this old post. I also had this issue and tried everything above but what worked for me was in each jest file I import the function at the top of the file like this:
`const { toBeInTheDocument } = require('@testing-library/jest-dom')`

Yes, it looks weird along with my esm imports but it worked. I'm using Typescript in my tests, and I probably don't understand the configuration enough to debug this.

I hope this can help someone.

**Comment by dondanhill** [comment]
For noobs like me out there, I resolved by adding the [NextJs example](https://github.com/vercel/next.js/blob/canary/examples/with-jest/jest.setup.js) file
