### ISSUE TITLE
Support arrays

### ISSUE THREAD

**Issue by C0DK** [testing-library/jest-dom#174]
### Describe the feature you'd like:
None of your matchers work with arrays, it seems, however the Testing library returns arrays in multiple of the possible queries.

### Describe alternatives you've considered:
Explain how to use your matchers with the jest in the current implemntation

### Teachability, Documentation, Adoption, Migration Strategy:
Examples could be:
All the matchers would be lovely with a `any` and `all` variant.
```
expect(getAllByRole("heading")).anyToHaveTextContent("Welcome!");
expect(getAllByRole("heading")).allToHaveClass("test-green");
```

**Comment by gnapse** [comment]
Related: testing-library/react-testing-library#550

**Comment by gnapse** [comment]
I don't think we're going to do this. For workarounds check the discussion in testing-library/react-testing-library#550.
