### ISSUE TITLE
JestMatchersShape<Matchers<void, HTMLElement>, Matchers<Promise<void>, HTMLElement>> doesn't has toBeVisible / toBeInDocument attributes

### ISSUE THREAD

**Issue by anyexinglu** [testing-library/jest-dom#178]
- `@testing-library/jest-dom` version: 4.2.4
- `node` version: 10.16.0
- `npm` (or `yarn`) version:  yarn v1.19.1

### Relevant code or config:

```tsx
// menu.test.tsx
expect(getByText('Option 5')).toBeVisible()

// scripts/expect.ts
import '@testing-library/jest-dom/extend-expect'

// jest.config.ts
setupFilesAfterEnv: ['<rootDir>/scripts/expect.ts']
```

### What you did:

I configure the @testing-library/jest-dom/extend-expect following [README.md Usage - 1](https://github.com/testing-library/jest-dom#usage)

### What happened:

The typescript definition doesn't work: 
```
类型“JestMatchersShape<Matchers<void, HTMLElement>, Matchers<Promise<void>, HTMLElement>>”上不存在属性“toBeVisible”。ts(2339)
```
![image](https://user-images.githubusercontent.com/8243326/71762644-d487bd00-2f0c-11ea-9f5e-d0d80908d319.png)

In English, the error means `JestMatchersShape<Matchers<void, HTMLElement>, Matchers<Promise<void>, HTMLElement>> doesn't has toBeVisible / toBeInDocument attributes`

### Related issue:

It seems pointed out before, but the solution doesn't work

https://github.com/testing-library/jest-dom/pull/11#issuecomment-387817459

**Comment by anyexinglu** [comment]
Sorry I can't reproduce the error a moment later.

It looks so strange, I tried reloading vscode window, restarting vscode and waited for a long time, the error always there...

So I went to do other things, then suddenly found the error disappeared and the definition shown.

![image](https://user-images.githubusercontent.com/8243326/71763815-3cdd9b00-2f1b-11ea-8d38-35baad9b905b.png)

So it works fine now, although I have done nothing to fix it.

**Comment by reinismu** [comment]
I have a similar error while running tests and using vscode. 

I have noticed that based on `some.test.ts` size it works or doesn't work. This is so annoying and I can't seem to understand where this behavior is coming from

**Comment by gnapse** [comment]
@reinismu we'd need a sample repo where this can be reproduced.

**Comment by ajdelossantos** [comment]
I've actually run into this same problem in my code. Jest will run the tests properly after a fresh reboot; when I revise the `.spec` file and save, I then get this error.

**Comment by loremaps** [comment]
I've run into this issue with vscode and running tests in watch mode. After doing a `--clearCache` everything works.

**Comment by ChinPTeo** [comment]
I had the same issue and fixed it by installing @types/testing-library__jest-dom, hope this helps someone

**Comment by zzswang** [comment]
> I had the same issue and fixed it by installing @types/testing-library__jest-dom, hope this helps someone

I run into this issue too, just init the project with [CRA](https://github.com/facebook/create-react-app).

And fixed it by add @types/testing-library__jest-dom package.
