### ISSUE TITLE
`toHaveStyle` support passing an object

### ISSUE THREAD

**Issue by tom-sherman** [testing-library/jest-dom#179]
### Describe the feature you'd like:

Pass an object to the `toHaveStyle` matcher. The object shape would be the same as the style object in React.

This would allow the tests to match the code conventions of a project using object-based CSS-in-JS and offer type checking/code completion.

### Teachability, Documentation, Adoption, Migration Strategy:

Offered as an alternative for the string function signature.

```javascript
expect(element).toHaveStyle({
  padding: '10px',
  marginTop: 5
});
```

**Comment by kentcdodds** [comment]
I'm in favor. I personally really like objects as styles. 👍

**Comment by gnapse** [comment]
I'm in favor too. And sorry for having left this issue forgotten. Should've replied earlier.

@tom-sherman are you interested and able to contribute with this enhancement? Otherwise I'd say we're open to have anyone else contribute. I may be able to take it eventually if no one jumps in.

**Comment by lourenci** [comment]
I can handle this if @tom-sherman doesn't want to.

**Comment by tom-sherman** [comment]
Please do crack on! I'm not going to have time for a couple of weeks, I can loop back around then and start if you haven't opened a PR.
