### ISSUE TITLE
`toHaveStyle` throw for wrong CSS syntax

### ISSUE THREAD

**Issue by MikeYermolayev** [testing-library/jest-dom#180]
Hi, looks like `toHaveStyle` doesn't throw when the style is totally missing or there are some errors in CSS syntax.

- `@testing-library/jest-dom` version: 4.1.0
- `node` version: 12.13.0
- `npm` (or `yarn`) version: yarn 1.21.1

- `react-testing-library` version: 9.1.3

### Relevant code or config:

```js
it(`should throw and it doesn't pass`, () => {
        const {container} = render(<div style={{display: `flex`}} />);

        expect(container.firstChild).toHaveStyle(`display: block`);
    });

it(`should throw but it passes without any errors`, () => {
        const {container} = render(<div style={{display: `flex`}} />);

        expect(container.firstChild).toHaveStyle(`height: 100`);
    });
```

### What you did:

Tried to test some style behavior and all tests were OK even for wrong CSS declaration

### What happened:

The code above doesn't throw when I pass style declaration with wrong syntax (i.e. 'px' is missing above)

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-4m3ge
(please go to test file)

### Problem description:

Sometimes it can be hard to notice small errors in CSS declaration but test start to pass. So it reduces reliability of tests

### Suggested solution:

Throw an error if there are syntax errors

Thanks in advance

**Comment by eps1lon** [comment]
This is very likely out of scope. It consume a lot of time to keep up with the CSS spec and we have to decide what spec/quirks we should support. 

Regarding the actual type being passed (passing a string when we expect an object): Consider using actual types via Flow or TypeScript. These are better suited than (potentially expensive) runtime type checking.

**Comment by MikeYermolayev** [comment]
Looks like using object signature proposed here #179  could help to avoid many problems.

For example I was trying to test for background-color like this:

```
expect(container.firstChild).toHaveStyle(`
  background-color: red,
`)
```

because of that comma after red the test always passes. With object signature it would keep you safe from that kind of mistakes

**Comment by kentcdodds** [comment]
Thanks for bringing this up @MikeYermolayev,

Yup. This is one of the reasons I prefer object styles as well :)

Nothing we're able to do here outside of that, so I'll close this in favor of #179
