### ISSUE TITLE
Add @types/testing-library__jest-dom as explicit dependency

### ISSUE THREAD

**Issue by leosuncin** [testing-library/jest-dom#185]
### Describe the feature you'd like:
In the new release [v5.0.0](https://github.com/testing-library/jest-dom/releases/tag/v5.0.0) said that the typings are now in `@types/testing-library__jest-dom` package, so, for a Typescript project to work is needed to install both as follows:
```bash
npm i -D testing-library/jest-dom @types/testing-library__jest-dom
```
[@testing-library/cypress](https://npm.im/@testing-library/cypress) has also its typings in separate package but is not necessary to explicit install the types because is a dependency of same package.

### Suggested implementation:
Add `@types/testing-library__jest-dom` as dependency in `package.json` so no need to worry about if you use Typescript.

### Describe alternatives you've considered:
The other alternative is to update the documentation to describe the need to install `@types/testing-library__jest-dom` for Typescript projects.

### Teachability, Documentation, Adoption, Migration Strategy:
I can do a pull request. Then it will be necessary a new release with a patch, maybe v5.0.1

**Comment by jgoz** [comment]
This is the plan, but it requires https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37792 to be merged. We had a chicken-and-egg scenario that unfortunately means 5.0.0 will not include typings but 5.0.1 will.

I would have added this to the release notes, but I don't know how to do that (haven't used semantic-release before). Sorry for the inconvenience &mdash; hopefully things will happen quickly.

**Comment by gnapse** [comment]
> I would have added this to the release notes, but I don't know how to do that (haven't used semantic-release before).

For the future: when you merged the PR that triggered the v5.0.0 release, you had the chance to edit the commit message. Whatever you include in the message (not just the first line but additional lines too) is included in the release notes.

We can also edit them after the fact here: https://github.com/testing-library/jest-dom/releases/edit/v5.0.0

(not sure if you have access, in which case let me know what to put there)

**Comment by jgoz** [comment]
Thanks @gnapse - looks great.

**Comment by coler-j** [comment]
Does this mean we do not need to explicitly install `@types/testing-library__jest-dom` for v greater than `5.0.1`?

**Comment by gnapse** [comment]
I think so. Have you tried that? Is it working or not for you?

**Comment by coler-j** [comment]
@gnapse I think it does work, yes.
