### ISSUE TITLE
Misleading documentation for toHaveFocus

### ISSUE THREAD

**Issue by jzarzeckis** [testing-library/jest-dom#186]
- `@testing-library/jest-dom` version: 5.0.0
- `node` version: v13.3.0
- `npm` (or `yarn`) version: 6.13.2

### Relevant code or config:
The unit test of [`toHaveFocus`](https://github.com/testing-library/jest-dom/blob/master/src/__tests__/to-have-focus.js) extended
```js
import {render} from './helpers/test-utils'
import document from './helpers/document'

test('.toHaveFocus', () => {
  const {container} = render(`
      <div>
        <label for="focused">test</label>
        <input id="focused" type="text" />
        <button type="submit" id="not-focused">Not Focused</button>
      </div>`)

  const focused = container.querySelector('#focused')
  const notFocused = container.querySelector('#not-focused')

  document.body.appendChild(container)
  focused.focus()

  expect(focused).toHaveFocus()
  expect(notFocused).not.toHaveFocus()

  expect(() => expect(focused).not.toHaveFocus()).toThrowError()
  expect(() => expect(notFocused).toHaveFocus()).toThrowError()

  // The proceeding lines were added to match the example in documentation
  focused.blur()
  expect(focused).not.toHaveFocus()

  focused.dispatchEvent(
    new focused.ownerDocument.defaultView.FocusEvent('focus', {
      bubbles: false,
      cancelable: false,
    }),
  )
  expect(focused).toHaveFocus()
})
```

### What you did:

I was trying to follow the documentation of `toHaveFocus`: https://github.com/testing-library/jest-dom#tohavefocus

It also provides the following example:
> Using DOM Testing Library
```js
const input = queryByTestId(container, 'element-to-focus')

fireEvent.focus(input)
expect(input).toHaveFocus()

fireEvent.blur(input)
expect(input).not.toHaveFocus()
```

### What happened:

As a result I expected my input would report having focus after calling fireEvent.

### Reproduction:

The example I provided in the beginning, matches what `dom-testing-library` does when one calls `fireEvent.focus(input)`

When I run the modified tests, it fails with:

```
 FAIL   jsdom  src/__tests__/to-have-focus.js
  ● .toHaveFocus

    expect(element).toHaveFocus()

    Expected
      <input id="focused" type="text" />
    Received:
      <body><div>
          <div>
            <label for="focused">test</label>
            <input id="focused" type="text" />
            <button id="not-focused" type="submit">Not Focused</button>
          </div></div></body>

      31 |     }),
      32 |   )
    > 33 |   expect(focused).toHaveFocus()
         |                   ^
      34 | })
      35 | 

      at Object.<anonymous> (src/__tests__/to-have-focus.js:33:19)
```
Because just firing an event doesn't change the focused element in jsdom.

### Problem description:

The problem is that either documentation is misleading, or this needs to be fixed in the implementation of `dom-testing-library`.

### Suggested solution:

To avoid confusion, the example with markdown can be removed. Of course it would be best to fix this in `dom-testing-library` instead, by calling `input.focus()`, when one calls `fireEvent.focus(input)`

**Comment by eps1lon** [comment]
Thank you for opening this detailed issue. It will help others discover this common misunderstanding.

You want to call `element.blur()` not `fireEvent.blur(element)`. Firing a event is really only doing that: firing an event. If you want other behavior to trigger as well use the DOM API e.g. [`HTMLElement.blur`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/blur) or [`HTMLElement.focus`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus)

**Comment by jzarzeckis** [comment]
Right. But the readme is still incorrect. Added a PR to just remove the misleading lines.
