### ISSUE TITLE
Cannot find module '@testing-library/jest-dom/matchers' 

### ISSUE THREAD

**Issue by nharrisanalyst** [testing-library/jest-dom#197]
I am getting the error 

Cannot find module '@testing-library/jest-dom/matchers' from 'selector.test.js'

are the docs correct it seems to work when I do 
import {
  toBeInTheDocument
} from '@testing-library/jest-dom

<img width="311" alt="image" src="https://user-images.githubusercontent.com/16217396/73485333-c1bfa700-4357-11ea-9376-7c8c13c36356.png">

<img width="216" alt="image" src="https://user-images.githubusercontent.com/16217396/73485423-e6b41a00-4357-11ea-9edd-c37b6f5ec4fb.png">

**Comment by gnapse** [comment]
Indeed. It seems we messed up when switching to v5. It's not enough to put a `matchers.js` file at the root. We also need to list it in the `files` entry of `package.json`, and not sure if that's enough.

**Comment by jgoz** [comment]
Adding it to `files` should be enough to make it work for JS users. There are no type definitions for `jest-dom/matchers`, so it will continue not working for TS users until someone adds them to DT.

**Comment by gnapse** [comment]
I wonder if, in addition to add it to `files`, we also need to stop using `import` and go back to `require`. Asking because I see that the root `extend-expect.js` does that when importing (or rather requiring) the corresponding `extend-expect.js` from inside `src/`.

**Comment by jgoz** [comment]
I think they can be left as `import` statements inside of `src`, but the `matchers.js` file itself should probably use `require`. It should also import the files from `dist` instead of `src`. And it should re-export using `module.exports`.

**Comment by gnapse** [comment]
I created #200 to tackle this. Tried those changes locally in a playground repo that uses jest-dom by selectively importing custom matchers and extending `expect` manually, and it works, whereas I confirmed it does not work with these changes in place, as @nharrisanalyst reported.
