### ISSUE TITLE
new matcher: toHaveAria

### ISSUE THREAD

**Issue by benmonro** [testing-library/jest-dom#199]
### Describe the feature you'd like:
seems like a pretty common pattern to use `expect(element).toHaveAttribute("aria-xxx", 'foo')` so thought maybe it would be nice to have a matcher just for aria: `expect(element).toHaveAria("xxx", "foo")`

it's mostly syntactical sugar, but just thought I'd see what folks think.

### Suggested implementation:
could just be a simple wrapper around `toHaveAttribute()`

**Comment by eps1lon** [comment]
I'm not a fan of increasing API surface i.e. adding more choices. Now users would have to decide: "Do I use `toHaveAttribute` or `toHaveAria`, and what is the difference?"

**Comment by lourenci** [comment]
I think we should stick with the purpose of the lib. 

> makes the test code more verbose, less clear in its intent, and/or harder to read.

**Comment by gnapse** [comment]
I echo @eps1lon and @lourenci. As the proposal even acknowledges, it's mostly syntactic sugar. The equivalent assertion with `.toHaveAttribute` is simple enough.
