### ISSUE TITLE
`.not.toBeInTheDocument()` fails when the element you are matching against isn't in the document

### ISSUE THREAD

**Issue by tom-sherman** [testing-library/jest-dom#202]
- `@testing-library/jest-dom` version: ^4.2.4
- `@testing-library/react` version: ^9.4.0
- `node` version: 10.13.0
- `npm` (or `yarn`) version: 6.4.1 (npm)

### Relevant code or config:

https://github.com/tom-sherman/jest-dom-nottobeindocument-bug

Specifically https://github.com/tom-sherman/jest-dom-nottobeindocument-bug/blob/master/src/App.test.js#L8

```javascript
expect(linkElement).not.toBeInTheDocument();
```

### What you did:

Added in a `.not` modifier before a `.toBeInTheDocument` call.

### What happened:

Test failed when it should have passed

### Reproduction:

Run `npm t` in this repo https://github.com/tom-sherman/jest-dom-nottobeindocument-bug

### Problem description:

I should be able to use `.not` modifiers on all jest-dom matchers.

**Comment by tom-sherman** [comment]
Oh I done goofed here...

I thought that the `.not.toBeInTheDocument` wasn't working correctly but in actual fact it was `getByText` thowing an error which is expected behaviour.

I can rewrite the test (https://github.com/tom-sherman/jest-dom-nottobeindocument-bug/commit/eca61346d83bec2a1d0212b916bc9a8852dcf6e9) to assert that this call throws.

**Comment by kalpeshsingh** [comment]
@tom-sherman - You may want to use `queryByText` instead of `getByText`. This way you don't need to check for `toThrow`.

**Comment by kalpeshsingh** [comment]
@tuzmusic I lost all the context of this issue. :D

Could you help us to understand relation of this with Storybook. A code sample might help too.

**Comment by tiomno** [comment]
> When running this in storybook, it's displaying `expect(null).not.toBeInTheDocument()`, as a passing test.
> 
> Is this correct?

@tuzmusic, it is. Check out the docs here https://testing-library.com/docs/queries/about/#types-of-queries in that table you'll see that `queryByText` returns **null** when matches no elements.
