### ISSUE TITLE
jest-dom seems to include dev dependencies in production

### ISSUE THREAD

**Issue by franciscop** [testing-library/jest-dom#205]
- `@testing-library/jest-dom` version: 5.1.1
- `node` version: v13.5.0
- `npm` (or `yarn`) version: 6.13.4

### Relevant code or config:

```
npm install @testing-library/jest-dom
```

### What you did:

Install jest-dom

### What happened:

I expected it to add few kb of size, but it added 45kb to my library. See bundlephobia for an example:

### Reproduction:

https://bundlephobia.com/result?p=@testing-library/jest-dom@5.1.1

### Problem description:

It _seems_ like some development libraries are included in `dependencies` instead of `devDependencies`. As a quick example, the heaviest dependency [according to Bundlephobia](https://bundlephobia.com/result?p=@testing-library/jest-dom@5.1.1) is `pretty-format`:

- It seems to [only be used in `tests/setup-env.js`](https://github.com/testing-library/jest-dom/search?q=pretty-format&unscoped_q=pretty-format).
- It is [defined as a dependency in package.json](https://github.com/testing-library/jest-dom/blob/master/package.json#L47) instead of a devDependency.

### Suggested solution:

I *think* (from the common JS patterns) that pretty-format might be a devDependency instead of a dependency, so I'd suggest moving it to devDependencies. It seems to be an internal dependency for testing jest-dom itself, so it should be defined as a `devDependency` instead to avoid including it in libraries that *wrap* jest-dom (as opposed to use jest-dom). [e.g. it is an issue here](https://github.com/franciscop/react-test/issues/15).

**Comment by eps1lon** [comment]
Well spotted. Would be great if you would work on a PR.

**Comment by franciscop** [comment]
Thanks! I'd love confirmation that `tests/setup-env.js` is _only_ used internally, otherwise this would break things. I can probably put a PR first for this and then review other dependencies

**Comment by eps1lon** [comment]
> I'd love confirmation that tests/setup-env.js is only used internally, otherwise this would break things.

Only used internally which is why I gave the PR a go.

**Comment by davidpaley** [comment]
@gnapse I am using version 5.11.6 of `testing-library/jest-dom` and Lighthouse is showing me that `@testing-library/dom` is still on the production bundle.
![image](https://user-images.githubusercontent.com/4527780/111467215-f11fa780-8702-11eb-917a-61f8bb69414f.png)

I am using this in devDependencies:
```
"@testing-library/jest-dom": "^5.11.6",
"@testing-library/react": "^9.5.0",
"@types/jest": "^23.3.14",
"jest": "^25.5.4",
"jest-dom": "^3.1.3",
"jest-environment-enzyme": "^7.1.2",
"jest-enzyme": "^7.1.2",
"jest-junit": "^11.1.0",
```

Anyone with the same problem?

**Comment by gnapse** [comment]
It does not seem related to jest-dom, given that it only uses this lib as a dev dependency, and you are using it as a dev dependency as well.

I took a look and other libs and `@testing-library/dom` has `pretty-format` in its `dependencies`. But I guess you'd have to be importing things in your app code for it to end in your build. Or maybe a library you are using has `@testing-library/dom` in their `dependencies` and not in their `devDependencies`. Not sure if `npm ls pretty-format` would help with figuring out from where are you getting the dependency.

**Comment by tohirul** [comment]
module not found can't resolve node_modules\react-scripts\node_modules\babel-loader\lib\index.js' in react 17

Okay so if there is anyone looking at this in 2022+ year, After downgrading from react-v18 to react-v17 I faced this issue. I had to run certain commands.

 1. npm install web-vitals@1.0.1

 2. npm install babel-loader --save-dev

 3. npm install -D babel-loader @babel/core @babel/preset-env webpack

I also moved my @testing-library/jest-dom,@testing-library/react,@testing-library/user-event to devDependencies and downgraded them

Worked like a charm.

**Comment by sohailupu** [comment]
> @gnapse I am using version 5.11.6 of `testing-library/jest-dom` and Lighthouse is showing me that `@testing-library/dom` is still on the production bundle. ![image](https://user-images.githubusercontent.com/4527780/111467215-f11fa780-8702-11eb-917a-61f8bb69414f.png)
> 
> I am using this in devDependencies:
> 
> ```
> "@testing-library/jest-dom": "^5.11.6",
> "@testing-library/react": "^9.5.0",
> "@types/jest": "^23.3.14",
> "jest": "^25.5.4",
> "jest-dom": "^3.1.3",
> "jest-environment-enzyme": "^7.1.2",
> "jest-enzyme": "^7.1.2",
> "jest-junit": "^11.1.0",
> ```


stlll i am facing same issue 
 FAIL  src/__test__/Login.test.js
  ● Test suite failed to run

    Cannot find module '@testing-library/jest-dom/extend-expect' from 'src/__test__/Login.test.js'

      1 | import React from "react";
    > 2 | import "@testing-library/jest-dom/extend-expect";
        | ^
      3 | import { render, screen, fireEvent } from "@testing-library/react";

**Comment by gnapse** [comment]
@sohailupu, how's that an example of the issue about dependencies appearing in your production bundle? It seems like a different issue than this one where we're discussing it, right? If you agree, please open a new issue. Or let me know if I'm missing something.
