### ISSUE TITLE
toBeChecked asserts true when checked=""

### ISSUE THREAD

**Issue by refinedblessing** [testing-library/jest-dom#222]
I am testing a Material UI Checkbox component, when component is checked, the input has attribute `checked="true"` but when unchecked it has attribute `checked=""`.

toBeChecked considers `checked=""` as it would consider `checked="true"` and asserts as checked.
I think an empty string should be considered as a false and unchecked in this case.

**Comment by eps1lon** [comment]
`checked` is a boolean attribute. This means that the underlying (reflected) property is `true` as soon as the attribute is present. In this case [`<input type="checkbox" checked="" />` is indeed a checked checkbox](https://jsfiddle.net/xyhucpsb/2/).

That is the reason we have this matcher in the first place. It's easy to get this wrong because most folks don't have to know about boolean attributes, reflected properties etc.

**Comment by mathias-falkenberg** [comment]
It goes a little deeper than that. The `checked` attribute [does not denote the current state](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#checked) but the initial state.

The checkbox can be correctly unchecked and still have `checked=""`. The matcher kind of gets it wrong. At least it seems to not quite do what the user expects.

Consider the following test:

```
const onChange = jest.fn();
const user = userEvent.setup();

render(<input type="checkbox" aria-label="foo" onChange={onChange} />);

const checkbox = screen.getByRole('checkbox', { name: 'foo' });

await user.click(checkbox);

expect(onChange).toHaveBeenCalledTimes(1);
expect(checkbox).toBeChecked();

await user.click(checkbox);
expect(onChange).toHaveBeenCalledTimes(2);
expect(checkbox).not.toBeChecked();
```

This passes as expected. However, invert the logic and the test (while it should be just as valid) now fails

```
const onChange = jest.fn();
const user = userEvent.setup();

render(<input type="checkbox" checked aria-label="foo" onChange={onChange} />);

const checkbox = screen.getByRole('checkbox', { name: 'foo' });

await user.click(checkbox);

expect(onChange).toHaveBeenCalledTimes(1);
expect(checkbox).not.toBeChecked();

await user.click(checkbox);
expect(onChange).toHaveBeenCalledTimes(2);
expect(checkbox).toBeChecked();
```
