### ISSUE TITLE
Support menuitemcheckbox/menuitemradio roles in toBeChecked

### ISSUE THREAD

**Issue by tf** [testing-library/jest-dom#266]
### Describe the feature you'd like:

According to the spec [`menuitemcheckbox`](https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#menuitemcheckbox) and [`menuitemradio`](https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#menuitemradio) both require `aria-checked` attributes.

I think it would be nice to be able to write:

```
expect(getByRole('menuitemradio', {name: 'Some option'})).toBeChecked();
```

### Suggested implementation:

Add `menuitemcheckbox` and `menuitemradio` to the [allowed roles in the matcher](https://github.com/testing-library/jest-dom/blob/0428c5c16ad80783fe0a033532c6dbd5436ff149/src/to-be-checked.js#L16).

### Describe alternatives you've considered:

So far, I was only able to use low level matchers like `toHaveAttribute('aria-checked', 'true')`.

### Teachability, Documentation, Adoption, Migration Strategy:

The roles would need to be added to list of allowed roles mentioned in [the readme](https://github.com/testing-library/jest-dom#tobechecked) and [the error messages](https://github.com/testing-library/jest-dom/blob/0428c5c16ad80783fe0a033532c6dbd5436ff149/src/to-be-checked.js#L25).

Happy to prepare a PR.

**Comment by tf** [comment]
Looking at the [spec of `aria-checked`](https://www.w3.org/TR/wai-aria-1.1/#aria-checked) again, I realized it would probably make sense to also add `option` and`treeitem`, the two other roles which support the attribute, while we are at it.

**Comment by eps1lon** [comment]
It's probably best to leverage `aria-query` if you want to make sure aria attributes are supported on a given role.

**Comment by tf** [comment]
Great idea. If it's fine to add the dependency, then the check could probably be implemented similar to [the way it is used in `dom-testing-library`](https://github.com/testing-library/dom-testing-library/blob/4ad36733bbd5d821b4e5878a76d9d9da9ce55dde/src/queries/role.js#L40). At the moment the error message explicitly lists all permitted roles. Do we want to preserve this behavior? If yes, should we iterate over all to find the ones supporting the attribute or is there a more convenient way?

**Comment by gnapse** [comment]
+1 to this feature request, and +1 to using something like `aria-query` for not having to maintain this logic ourselves.

> At the moment the error message explicitly lists all permitted roles. Do we want to preserve this behavior? If yes, should we iterate over all to find the ones supporting the attribute or is there a more convenient way?

I'd say that, unless it becomes cumbersome while implementing this to achieve it, it'd be nice if we can preserve that bit of functionality. At worse we can discuss and decide in the context of the PR when someone jumps on implementing this.

**Comment by tf** [comment]
I've submitted PR #267. Happy to incorporate feedback.
