### ISSUE TITLE
toHaveStyle does not compare empty values

### ISSUE THREAD

**Issue by just-boris** [testing-library/jest-dom#272]
- `@testing-library/jest-dom` version: 5.11.0
- `node` version: 12.17.0
- `npm` (or `yarn`) version: 6.14.4

### Relevant code or config:

```js
test('div max-width', () => {
  const div = document.createElement('div');
  div.style.maxWidth = '300px';
  div.style.minWidth = '200px';
  expect(div).toHaveStyle({ minWidth: '200px', maxWidth: '' }); // passes, but it should not
});
```

I expect that this assertion will fail, because `maxWidth` is not empty.

It works, when I am using `toEqual` instead of `toHaveStyle`

```
expect(div.style).toEqual(expect.objectContaining({ minWidth: '200px', maxWidth: '' }));
```

### Suggested solution:

Somehow this information about empty values is lost around these lines: 

https://github.com/testing-library/jest-dom/blob/7ea936d62cfda3aaa6f4ee9a2b7a0aa576e2e55a/src/to-have-style.js#L60-L61

A potential fix would be to check that all keys are from the expectation are defined on the element style definition.

**Comment by lourenci** [comment]
It's working for me. Can you reproduce in a codesandbox, please?

![image](https://user-images.githubusercontent.com/2339362/86651288-c7ca4b80-bfb9-11ea-8771-b4b5a8c98ce3.png)

**Comment by just-boris** [comment]
Yes, reproduced in CodeSandbox: https://codesandbox.io/s/react-testing-library-demo-3c133?file=/src/__tests__/hello.js

it works fine if it was the only style property. When there are more, it gives false-positive. I also updated the original issue description

**Comment by lourenci** [comment]
I can confirm the bug. I don't know how to solve it yet, but:

We underlie on the DOM API to parse the expected CSS object in a CSS before we compare it against the element's computed style, this API removes any invalid CSS attribute and it does not care about an "unset" attribute. 

So in your example, the matcher ends up comparing partially against the element.
```
  const div = document.createElement('div');
  div.style.maxWidth = '300px';
  div.style.minWidth = '200px';
  expect(div).toHaveStyle({ minWidth: '200px', maxWidth: '' }); // the API will remove the empty string attribute (maxWidth) and it will match only against minWidth.
```

**Comment by just-boris** [comment]
I don't understand, why we need to serialize styles to string and then parse it back, losing the information about empty but defined keys.

The color normalization is being done later in [another function](https://github.com/testing-library/jest-dom/blob/7ea936d62cfda3aaa6f4ee9a2b7a0aa576e2e55a/src/to-have-style.js#L10-L14), why `parseCSS` is needed for object syntax?

**Comment by lourenci** [comment]
I don't know if I got your question, but we need to normalize the expected value to match it against the element's css.

An element with the style `background-color: red; min-width: 200px` has to match against both `toHaveStyle`s (no matter what is the order):
```
expect(element).toHaveStyle('min-width: 200px; background-color: red')
expect(element).toHaveStyle({ minWidth: '200px', backgroundColor: 'red' })
```

**Comment by just-boris** [comment]
Yes, parsing CSS makes sense for the CSS-as-string argument. However, for the object format, it seems redundant, because keys order usually does not affect object equality.

Is there a chance to refactor the code and make `toHaveStyle` implementation for the object mode simpler, just `expect(element.style).toHaveStyle({...})` with extra colors normalization?

**Comment by lourenci** [comment]
I got your point. I think it could work. Do you want to try it?

**Comment by just-boris** [comment]
Yes, I will give it a try and come back with a PR if this works out.

**Comment by just-boris** [comment]
The PR is out: #276
