### ISSUE TITLE
userEvent.type do not set provided string to textarea 

### ISSUE THREAD

**Issue by rohitchhabra1** [testing-library/jest-dom#273]
- `@testing-library/jest-dom` version:
- `node` version:
- `npm` (or `yarn`) version:

### Relevant code or config:

```js
var your => (code) => here;
```

### What you did:
  userEvent.type(textarea, "Greeting");
  expect(textarea.value).toBe("Greeting");

### What happened:
![image](https://user-images.githubusercontent.com/40591871/86922741-b2d0f200-c14a-11ea-8c06-6b418d2f98fa.png)

**Comment by lourenci** [comment]
Hi, @nickmccurdy. Can you move this issue to user-event, please?

I think it's could be related to https://github.com/testing-library/user-event/issues/391.

**Comment by rohitchhabra1** [comment]
thanks
