### ISSUE TITLE
Got TypeError: expect(...).toBeInTheDocument is not a function even after proper setup

### ISSUE THREAD

**Issue by inovramadani** [testing-library/jest-dom#282]
- `@testing-library/jest-dom` version: 4.2.4
- `node` version: 10.15.1
- `npm` (or `yarn`) version: 6.13.4

### Problem description:

I use Create React App and already declare this on src/setupTests.js: 

```javascript
import '@testing-library/jest-dom';
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });
```

But every time I use `expect(anything).toBeInTheDocument()` on test file, when running the test I get:  
```
TypeError: expect(...).toBeInTheDocument is not a function
```

To make sure that the setupTests.js is actually run, I try to use enzyme shallow on test file and it works. So what is the problem with jest-dom actually and how to solve it?

**Comment by inovramadani** [comment]
Solved with:
```
import '@testing-library/jest-dom/extend-expect';
```
on src/setupTests.js

**Comment by nickmccurdy** [comment]
You should only need this:

```js
import '@testing-library/jest-dom';
```

Try upgrading it with `npm update --latest @testing-library/jest-dom`
