### ISSUE TITLE
toBeInTheDocument error with material-ui icons

### ISSUE THREAD

**Issue by lpeliberty** [testing-library/jest-dom#293]
Hello, I think this is a bug but I'm not sure because I'm not an expert on your great lib !
Everything you need is in codesandbox reproduction.

### What happened:

Error on test `expect(wrapper.find(CloseIcon)).toBeInTheDocument();`
But with classic `expect(wrapper.find(CloseIcon)).toHaveLength(1);` it works... This is why I think it's a bug.

### Reproduction:

https://codesandbox.io/s/morning-river-ymv5b?file=/src/App.test.js

### Problem description:

received value must be an HTMLElement or an SVGElement.
Received has type:  object
Received has value: {}

**Comment by eps1lon** [comment]
Enzyme does not return actual DOM elements but custom objects. This library does not support wrappers from enzyme.

**Comment by nickmccurdy** [comment]
Note that this is designed to work with [React Testing Library](https://github.com/testing-library/react-testing-library) which uses actual DOM elements.
