### ISSUE TITLE
introduce hamjest versions of the custom matchers 

### ISSUE THREAD

**Issue by richardwan** [testing-library/jest-dom#296]
### Describe the feature you'd like:

I love these jest-dom custom matchers.  I would love them even more if there were hamjest https://github.com/rluba/hamjest versions of them and would be happy to introduce hamjest versions.  the hamjest "matchers" (inspired by hamcrest/jUnit) compose more easily into more matchers without the need to write "more custom matchers".  

For example: if the there were a hamjest version of `toBeVisible()` called `visible()` we could write `expect(element).toBe(visible())` and this would open the door to easy compositions with existing hamjest matchers like `hasItem`  to write things like `expect(element.querySelectorAll('option')).to(haveItem(visible()))`

If there is interest in this feature I would be happy to implement it and create a PR.

The biggest drawbacks I see:
  - introduces a dependency on hamjest (and so maybe this would make more sense as a new library called hamjest-dom)
  - maintaining both the current matchers and the hamjest versions. 

### Suggested implementation:

- introduce a single custom matcher called "toBe" and delegates to `assertThat` in hamjest. so that `expect(5).toBe(greaterThan(3))` winds up being equivalent to `assertThat(5, greaterThan(3))`
- create hamjest/hamcrest matchers corresponding to the jest-dom matchers
- optional: retrofit current jest-dom matchers to call the hamjest versions.   (e.g. `toBeVisible()` could be retrofitted as `toBeVisible() => {to(beVisible())}`) 

### Describe alternatives you've considered:

- create a new hamjest-dom repo which is functionally equivalent to jest-dom but uses hamjest style matchers instead of custom asserts

### Teachability, Documentation, Adoption, Migration Strategy:

Will introduce examples similar to
- `expect(element).toBe(visible())` 
- `expect(element.querySelectorAll('option')).to(haveItem(visible()))`

that shows how to use a hamjest equivalent of a current jest-dom matcher and how to compose these hamjest versions to achieve functionality that possible with the current jest-dom

**Comment by gnapse** [comment]
Interesting idea. Though as you said, it seems like a different approach that would mirror/supersede most of our matchers in the form they exist today. I'm more inclined to first explore it as a separate prototype lib, and maybe it can stay that way or be absorbed.

Is there an example of jest being combined with hamjest? In spite of the name, this hamjest lib does not seem to be related or even geared towards being used with jest.

About this:

> introduce a single custom matcher called "toBe"

There's [a built-in `toBe` in jest](https://jestjs.io/docs/en/expect.html#tobevalue) already.

---

Tangentially related so I'll mention it on the side:

Also, there's already a jest mechanism to provide more dynamic values to some matchers. For instance, you can do things such as validating that a value is an array containing a certain value:

```js
expect(['Alice', 'Bob', 'Eve']).toEqual(expect.arrayContaining('Bob'));
```

We make some use of these, allowing to use them in some of our matchers. For example

```js
// passes for type="button" and type="submit"
expect(button).toHaveAttribute('type', expect.stringContaining('b'))
```

**Comment by richardwan** [comment]
oh, i mistakenly thought hamjest was an "add on" to jest.

**Comment by gnapse** [comment]
So do you think there's an actionable here regardless of this mix up? If not I'd rather close this, which does not preclude it from being re-opened or to continue the discussion.

**Comment by richardwan** [comment]
I'll close.  If I find more relevant info, I'll post it into the discussion.
