### ISSUE TITLE
How to make it work with typescript?

### ISSUE THREAD

**Issue by yaquawa** [testing-library/jest-dom#297]
I'm using jest with ts-jest, so I'm wondering is there any way to make this lib work with test files written by typescript?

**Comment by nickmccurdy** [comment]
Are you having any errors or do you just want to set up your tests? For the most part, things should just work with `ts-jest` if you also install `@types/testing-library__jest-dom`.

**Comment by yaquawa** [comment]
seems like I have to write: `import '@testing-library/jest-dom'`.
Is this the right way to do it?

**Comment by nickmccurdy** [comment]
That's the right way to import it, yes, but you need to install `@types/testing-library__jest-dom` with your package manager too (npm/yarn/pnpm/etc)

**Comment by yaquawa** [comment]
Got it , thanks!
