### ISSUE TITLE
Firing click should fire mouseDown and mouseUp

### ISSUE THREAD

**Issue by SunriseM** [testing-library/jest-dom#316]
- `@testing-library/jest-dom` version: 11.2.2
- `node` version: 12.18.2
- `npm` (or `yarn`) version: npm 6.14.5

### Relevant code or config:

```js
fireEvent.click(screen.getByTestId('modal-overlay'))
```

I was expecting `.click` to fire the events `onMouseDown` and `onMouseUp` as the `click` event is fired after those but it's not the case.

It looks important to me because sometimes the component's logic depends on the fact that `onMouseDown/onMouseUp` are fired before `click`

I'm open to making this change if you are ok with it.

**Comment by SunriseM** [comment]
woops wrong repo

**Comment by eps1lon** [comment]
Continued in https://github.com/testing-library/react-testing-library/issues/852
