### ISSUE TITLE
Input `minlength` violations do not result in an invalid element

### ISSUE THREAD

**Issue by rschristian** [testing-library/jest-dom#351]
- `@testing-library/jest-dom` version: 5.11.10
- `node` version: 14.16.0
- `npm` version: 6.14.11

* `@testing-library/preact` version: 2.0.1

### Relevant code or config:

```jsx
it('validates password input', () => {
    render(<input type="text" minLength={8} aria-label="Input" />);
    
    const input = screen.getByRole('textbox', { name: 'Input' });

    fireEvent.input(input, { target: { value: 'foobar' } });
    expect(input).toBeInvalid(); <-- expect fails, as the element is somehow valid, even with a length below the specified minlength
});
```

### What you did:

I was trying to test that an input would be invalid with a content length under the minimum set by the element.

### What happened:

The element is valid, even when it should not be

### Reproduction:

Here's an example of the the input being rejected in the browser:

https://esm.codes/#Ly8gSmVzdC1Eb20gYnVnCi8vIC0tLS0tLS0tLS0tLS0tLS0KICAgIAppbXBvcnQgeyBodG1sLCByZW5kZXIsIHVzZVN0YXRlLCB1c2VSZWYgfSBmcm9tICdodHRwczovL3VucGtnLmNvbS9odG0vcHJlYWN0L3N0YW5kYWxvbmUubW9kdWxlLmpzJwoKY29uc3QgYXBwID0gKCkgPT4gewogIGNvbnN0IGlucHV0UmVmID0gdXNlUmVmKCk7CiAgY29uc3QgW3ZhbGlkLCBzZXRWYWxpZF0gPSB1c2VTdGF0ZShmYWxzZSk7CiAgCiAgcmV0dXJuIGh0bWxgCiAgICA8aW5wdXQgcmVmPSR7aW5wdXRSZWZ9IHR5cGU9InRleHQiIG1pbmxlbmd0aD04IG9uSW5wdXQ9JHsoKSA9PiBpbnB1dFJlZi5jdXJyZW50LmNoZWNrVmFsaWRpdHkoKSA/IHNldFZhbGlkKHRydWUpIDogc2V0VmFsaWQoZmFsc2UpfSAvPgogICAgPGRpdiBzdHlsZT0iY29sb3I6ICR7dmFsaWQgPyAnd2hpdGUnIDogJ3JlZCd9OyBtYXJnaW4tdG9wOiAxcmVtIj4ke3ZhbGlkID8gJ1ZhbGlkJyA6ICdJbnZhbGlkJ308L2Rpdj4KICBgCn0KCnJlbmRlcihodG1sYDwke2FwcH0gLz5gLCBkb2N1bWVudC5ib2R5KQ==

Silly little input field. Enter 8 or more characters and the `Invalid` text will switch to `Valid`. 

This test should therefor pass, as `foobar` is 6 characters, while 8 are called for. However, the element in not invalid for some reason.

```jsx
import { h } from 'preact';
import { render, screen, fireEvent } from '@testing-library/preact';

it('validates password input', () => {
    render(<input type="text" minLength={8} aria-label="Input" />);
    
    const input = screen.getByRole('textbox', { name: 'Input' });

    fireEvent.input(input, { target: { value: 'foobar' } });
    expect(input).toBeInvalid();
});
```

### Problem description:

Using `checkValidity()` of an input with minlegth set will result in that element being invalid if the content length is less than the specified minimum. `jest-dom` calls it valid regardless.

### Suggested solution:

No idea really. Seems to be calling `checkValidity()` as I'd expect.

**Comment by gnapse** [comment]
> No idea really. Seems to be calling `checkValidity()` as I'd expect.

Maybe this is a problem with jsdom? As you mentioned, [jest-dom relies on the DOM APIs to tell if the element is considered invalid](https://github.com/testing-library/jest-dom/blob/21ad89bc707b6e41af887d1bd103dd6dbc665dee/src/to-be-invalid.js#L19) by the browser. But jest-dom does not check validity itself. If our browser is giving us incorrect results, there's little we can do.

**Comment by rschristian** [comment]
Ah, apologies then. I'll bring this elsewhere.

Thanks for your time.
