### ISSUE TITLE
Latest update breaks partial html matcher like `<a`. This used to work.

### ISSUE THREAD

**Issue by ZachMayry** [testing-library/jest-dom#352]
- `@testing-library/jest-dom` version: 5.11.10
- `node` version: v14.15.4
- `npm` (or `yarn`) version: yarn 1.21.1

### Relevant code or config:
paraphrased some of the code and changed to `stuff`/`asdf`
```js
<div data-testid="Editor">
    {stuff.map((asdf) => <a href="http://localhost">{asdf}</a>)}
</div>
```

```js
expect(screen.getByTestId('Editor')).not.toContainHTML('<a')
```

### What you did:

Running the test. This passes in 5.11.9

### What happened:

```
Error: expect(element).not.toContainHTML()
Expected:
  <a
Received:
  <div data-testid="Editor"></div>
```

### Problem description:

seem like partial html (which used to work) is now being removed when it's normalized

### Suggested solution:

Maybe you could do something like this
```js
pass: container.outerHTML.includes(getNormalizedHtml(container, htmlText)) || container.outerHTML.includes(htmlText)
```

**Comment by ZachMayry** [comment]
We ended up just refactoring the test so no worries if this isn't something you're going to support anymore moving forward.
But this may help others

**Comment by gnapse** [comment]
Indeed, this was supported accidentally, as this was never the intention of this matcher. Glad you sorted it out.
