### ISSUE TITLE
Drop Node 12 support

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/jest-dom#366]
Because it's [EOL](https://nodejs.org/en/about/releases).

**Comment by gnapse** [comment]
Related:

- https://github.com/testing-library/dom-testing-library/issues/957
- https://github.com/testing-library/react-testing-library/issues/913

**Comment by nickmccurdy** [comment]
@IanVS Enough time has passed that 14 has already reached end of life. Do we need to ship additional breaking changes to resolve the new issues with Jest DOM 16?
