### ISSUE TITLE
Types for 5.14.1 have not been published yet

### ISSUE THREAD

**Issue by icatalina** [testing-library/jest-dom#383]
- `@testing-library/jest-dom` version: 5.14.1
- `node` version: 14
- `npm` (or `yarn`) version: 7

### Problem description:

The most recent version of the types from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__jest-dom hasn't been published yet. This causes issues where new matchers can't be used and old matchers are flagged as deprecated.

### Suggested solution:

I'm not sure how `DefinitelyTyped` publication process works, should they be publish automatically? the changes where merged 11 days ago 😕

**Comment by rinalu** [comment]
Any updates on this issue?

**Comment by icatalina** [comment]
https://www.npmjs.com/package/@types/testing-library__jest-dom still not published

**Comment by icatalina** [comment]
Turns out the solution was to uninstall and reinstall `@testing-library/jest-dom`, it seems like our lock file was stuck on an old version of the types.
