### ISSUE TITLE
Сan't use getByTestId() for doesn't exist components

### ISSUE THREAD

**Issue by a5okol** [testing-library/jest-dom#391]
Custom jest matchers **[.not.toContainElement](https://github.com/testing-library/jest-dom#tocontainelement)** and **[.not.toBeInTheDocument](https://github.com/testing-library/jest-dom#tobeinthedocument)** cannot be applied because const nonExistantElement = getByTestId('does-not-exist') throws an error "TestingLibraryElementError: Unable to find an element by: [data-testid="collection-filter-modal"]"

<img width="557" alt="Screenshot 2021-07-28 at 09 52 13" src="https://user-images.githubusercontent.com/57001613/127277439-11d16809-c396-4b99-879d-1f9b587e29ea.png">

**Comment by gnapse** [comment]
This is a feature, not a bug. The `getBy*` helpers from dom-testing-library are meant to also make sure the element you are requesting exist, and they raise an exception. If you want to query for elements in the DOM that might not exist, you should use the `queryBy*` helpers instead. These return `null` or `undefined` (not sure which one) if the element you queried for is not found. You can then use them alongside `.not.toBeInTheDocument()`, etc.

**Comment by Jaxolotl** [comment]
you can always wrap it to capture the exception

`await waitFor(() => expect(() => getByTestId('THEID')).toThrow());`
or
`await waitFor(() => expect(() => getByTestId('THEID')).toThrow('Unable to find an element by: [data-testid="THEID"]'));`
