### ISSUE TITLE
Dom not clearing properly between tests when using notification or message 

### ISSUE THREAD

**Issue by balboFK** [testing-library/jest-dom#411]
```
"node version": 14.16.1
"react": "^17.0.2",
"react-dom": "^17.0.2",
"@testing-library/dom": "^8.7.2",
"@testing-library/jest-dom": "^5.14.1",
"@testing-library/react": "^12.1.2",
"antd": "^4.16.13",
```

Hello everybody!
I'm trying to test the functionality of a notification on my app, and when I have more than one test who asserts on said notification being shown, I get this problem.
I think that's maybe because the DOM is not properly cleaned between tests, and it still happens even if I use "cleanup", so the compiler end's up finding more than one element and breaking the tests.
Any idea why, and how should i test this?

What you did:
Tried to assert that only one notification should be on screen between tests

What happened:
The test fails because it finds more than one notification

Reproduction:
https://codesandbox.io/s/react-testing-library-demo-forked-zzqt5?file=/src/__tests__/hello.js

Suggested solution:
Clear the whole DOM between each tests maybe?

**Comment by gnapse** [comment]
Hi @balboFK, thanks for taking the time to report this issue. Having a codesandbox example to reproduce was invaluable, so keep doing that when reporting issues to OSS projects in general.

In this particular case, I have two observations:

1. jest-dom is not responsible for managing your DOM, by which I mean that a potential issue with the DOM not being cleaned up between tests is out of our domain. This is more related to the `cleanup` function, which we do not control, as it is in the React testing library.
2. The `cleanup` function cleans up from the DOM anything that you've mounted using the `render` function. But these notifications that you're talking about are not managed via React. I see that you use a library called `antd` that renders notifications in some other way, presumably by directly injecting them to the DOM or manipulating the DOM somehow. Therefore, any elements it introduces are not cleaned up by `cleanup`. The `cleanup` functions cleans up anything that was rendered via `render`.

So I guess that what you need is, either:

1. Have your component's effect clean up after itself, removing the notification from the UI after the component unmounts.
2. Or, if you do want your floating notifications to outlive your component and respect a potential timeout, then you have to configure jest to that in the `afterEach` you somehow tell this `antd` library to cleanup its own stuff.

Hope this helps. I'm going to close this issue, but we can continue the discussion. And feel free to reopen if I somehow managed to misunderstand all this, and what I just said makes no sense to you.

**Comment by rickvian** [comment]
Thank you, i found this discussion 

i was having similar issue but with ANTD Modal 
it seems like behave similar way

we dig into ANTD library tests,
they use command Modal.destroyAll() beforeEach to properly clean up the modal
