### ISSUE TITLE
Update aria-query to avoid babel runtime

### ISSUE THREAD

**Issue by IanVS** [testing-library/jest-dom#413]
### Describe the feature you'd like:

I'd like to suggest an update to aria-query@5.  They removed their usage of Map and Set, and by doing so, removed babel as runtime dependencies.  I'm currently struggling with one of the babel dependencies that is being brought in to my project via this package, and it could save disk space for other consumers who are not using babel as well.

**Comment by aleksaToljic** [comment]
This is breaking my build for some reason, not sure why, i'll try to investigate untill then, I'll avoid this version.
It's a public repo:
https://github.com/filecoin-project/system-test-matrix/pull/203
