### ISSUE TITLE
TS error when using vitest globals and @testing-library/jest-dom

### ISSUE THREAD

**Issue by robcaldecott** [testing-library/jest-dom#427]
- `@testing-library/jest-dom` version: 5.16.1
- `node` version: 14.17.0
- `yarn` version: 1.22.17
- `@testing-library/react` version: 12.1.2

I am using `vitest` instead of `jest` for testing a React component lib in a monorepo. I am using `@testing-library/jest-dom` and `@testing-library/react` and both happily work with `vitest`.

However, when type checking my code I am seeing a clash between `@types/jest` and `vitest`. The `@types/jest` dependency seems to have been pulled in by  `@testing-library/jest-dom`.

```
../node_modules/@types/jest/index.d.ts:34:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: test, describe, it, expect, beforeAll, afterAll, beforeEach, afterEach

34 declare var beforeAll: jest.Lifecycle;
   ~~~~~~~

  ../node_modules/vitest/global.d.ts:1:1
    1 declare global {
      ~~~~~~~
    Conflicts are in this file.

../node_modules/vitest/global.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: test, describe, it, expect, beforeAll, afterAll, beforeEach, afterEach

1 declare global {
  ~~~~~~~

  ../node_modules/@types/jest/index.d.ts:34:1
    34 declare var beforeAll: jest.Lifecycle;
       ~~~~~~~
    Conflicts are in this file.


Found 2 errors.
```

It would be great to have a workaround for this issue so the `jest` types can be removed or ignored.

To reproduce this issue clone the following project (notice it uses a branch called `yarn`):

https://github.com/robcaldecott/pnpm-vite-monorepo-example/tree/yarn

To see the error:

```
yarn install
cd components
yarn build
```

**Comment by sheremet-va** [comment]
Related: https://github.com/vitest-dev/vitest/issues/517

**Comment by dancras** [comment]
Simply removing the following line from the [types definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__jest-dom/index.d.ts) solves it and doesn't impact the functionality from my brief testing.

```
/// <reference types="jest" />
```

If anyone wants a hacky and crude solution in the meantime:

package.json
```
  "scripts": {
    "build": "node patchJestDom.js && %previous_build_commands%",
  }
```

patchJestDom.js
```
import fs from 'fs';
import path from 'path';

const typesPath = path.resolve('node_modules', '@types', 'testing-library__jest-dom', 'index.d.ts');

fs.readFile(typesPath, 'utf8', (err, data) => {
    if (err) throw err;

    let lines = data.split('\n');

    if (lines[8] === '/// <reference types="jest" />') {
        lines = lines.slice(0, 8).concat(lines.slice(9));
    }

    fs.writeFile(typesPath, lines.join('\n'), 'utf8', function(err) {
        if (err) throw err;
    });
});
```

**Comment by larsenwork** [comment]
@dancras thanks for the hack, currently using it too but added to `postinstall` lifecycle script to have it run on both https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-ci and https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-install

```
  "scripts": {
    ...existing scripts here,
    "postinstall": "node scripts/patchJestDom.js",
  }
```

**Comment by rud4z** [comment]
Thanks @dancras, your solution worked! I had to modify it because my reference to jest was on line 10, so I ended up making it to recognize any line:
```javascript
const fs = require("fs");
const path = require("path");

const typesPath = path.resolve(
  "node_modules",
  "@types",
  "testing-library__jest-dom",
  "index.d.ts"
);

fs.readFile(typesPath, "utf8", (err, data) => {
  if (err) throw err;

  let lines = data.split("\n");

  jestTypesIndex = lines.findIndex((line) =>
    line.includes('reference types="jest"')
  );

  if (lines[jestTypesIndex] === '/// <reference types="jest" />') {
    lines = lines
      .slice(0, jestTypesIndex)
      .concat(lines.slice(jestTypesIndex + 1));
  }

  fs.writeFile(typesPath, lines.join("\n"), "utf8", function (err) {
    if (err) throw err;
  });
});
```

**Comment by larsenwork** [comment]
FWIW this works just fine too. (I tend not to care about throwing errors because they are of limited value in a build step like this) 

```ts
import fs from 'fs'
import path from 'path'

const typesPath = path.resolve('node_modules/@types/testing-library__jest-dom/index.d.ts')
const encoding = 'utf8'
const strings = {
  search: '/// <reference types="jest" />',
  replace: '// See https://github.com/testing-library/jest-dom/issues/427 for reference',
}

const result = fs
  .readFileSync(typesPath, encoding)
  .replace(strings.search, strings.replace)

fs.writeFileSync(typesPath, result, encoding)
```

**Comment by airjp73** [comment]
Tried the workaround above, but had to tweak one thing. In `global.d.ts` I had to write this instead:

```ts
import type { TestingLibraryMatchers } from "@testing-library/jest-dom/matchers";

declare global {
  namespace jest {
    interface Matchers<R = void>
      extends TestingLibraryMatchers<typeof expect.stringContaining, R> {}
  }
}
```

**Comment by cmacdonnacha** [comment]
> Tried the workaround above, but had to tweak one thing. In `global.d.ts` I had to write this instead:
> 
> ```ts
> import type { TestingLibraryMatchers } from "@testing-library/jest-dom/matchers";
> 
> declare global {
>   namespace jest {
>     interface Matchers<R = void>
>       extends TestingLibraryMatchers<typeof expect.stringContaining, R> {}
>   }
> }
> ```

Hey @airjp73 , what does your `tsconfig.ts` file look like? I keep getting an error when importing:

![image](https://user-images.githubusercontent.com/9777763/169059093-e69bf948-5e7a-404f-a675-0797fc00b9bb.png)

**Comment by cmacdonnacha** [comment]
Not sure if this is the correct solution but adding `"skipLibCheck": true,` in my `tsconfig.json` fixed it.

**Comment by edumudu** [comment]
for me, using `vitest@0.16.0` and `@testing-library/jest-dom@5.16.4` only the solution bellow worked

```ts
// global.d.ts
import type { TestingLibraryMatchers } from '@testing-library/jest-dom/matchers';

type CustomMatchers<R = unknown> = TestingLibraryMatchers<typeof expect.stringContaining, R>;

declare global {
  namespace Vi {
    interface Assertion extends CustomMatchers {}
    interface AsymmetricMatchersContaining extends CustomMatchers {}
  }
}
```

and using `pnpm` the code bellow need to be placed in the `.npmrc` to be able to use the `TestingLibraryMatchers` types outside `node_modules`
```yml
shamefully-hoist = true
```

**Comment by jsjoeio** [comment]
Combining @BPreisner and @airjp73's solutions, I made a new template to save myself (and others) future time: https://github.com/jsjoeio/react-ts-vitest-template

**Comment by seivan** [comment]
> @gnapse is there any possibility to remove `/// <reference types="jest" />` from library types and make `@types/jest` a peerDependency?
> 
> Anyway, I found a slightly less hacky workaround 💯 :
> 
> `setupTests.ts` (file which goes to `test.setupFiles` in `vite.config.ts`)
> 
> ```ts
> import '@testing-library/jest-dom/extend-expect';
> ```
> 
> `global.d.ts` (file placed in root or inside `src` directory)
> 
> ```ts
> /* eslint-disable @typescript-eslint/ban-types */
> /* eslint-disable @typescript-eslint/no-unused-vars */
> import type { TestingLibraryMatchers } from '@testing-library/jest-dom/matchers';
> 
> declare global {
>   namespace jest {
>     type Matchers<R = void, T = {}> = TestingLibraryMatchers<
>       typeof expect.stringContaining,
>       R
>     >;
>   }
> }
> ```
> 
> `tsconfig.json`
> 
> ```json
> {
>   "compilerOptions": {
>    ...
>     "types": ["node", "vite/client", "vitest/globals"],
>   },
> }
> ```


Out of curiosity, would this have worked? 

```ts
  "compilerOptions": {
    "typeRoots": [],
    "types": [],
    }
    ```

That's my default setting as I loathe polluted namespaces. 
I know it doesn't fix the root problem of them bundling the types. 
But am wondering ( can't test it right now) if augmenting the jest namespace would be needed if `types` settings are set to not include by default.

**Comment by zoontek** [comment]
I made a simple solution to fix this issue: https://github.com/zoontek/types-testing-library-vitest-dom

**Comment by kaorun343** [comment]
How about providing `@testing-library/vitest-dom` ?
Since the release of Vitest, the number of downloads of Vitest has increased.
I think the official support for using testing library with vitest makes us very happy and there will be no need to ad-hoc solutions.

**Comment by nickmccurdy** [comment]
I don't think making a new package is worth the cognitive/maintenance overhead when we could just make this package more framework agnostic.

**Comment by AndrewLeedham** [comment]
Would the workaround here work for this? https://github.com/testing-library/jest-dom/issues/439

**Comment by nickmccurdy** [comment]
Are you suggesting we document this as a temporary workaround for Vitest users, or expose a Vitest entry point permanently?

**Comment by AndrewLeedham** [comment]
> Are you suggesting we document this as a temporary workaround for Vitest users, or expose a Vitest entry point permanently?

Currently a workaround, I can see why the requirement of `types: []` would be a pain, I was already using that to get around Cypress conflicts, but not an ideal solution. Maybe the inverse would be a cleaner solution, where we provide `jest.d.ts` and `vitest.d.ts` and the matchers are just exported from the index, so you have to do something like `/// <reference types="@testing-library/jest-dom/vitest" />` in your `jest-setup.ts` script instead of excluding the index with `types: []`?

**Comment by elliottsj** [comment]
>Maybe the inverse would be a cleaner solution, where we provide `jest.d.ts` and `vitest.d.ts`

I like this approach as well.

For now, I am using a workaround with [`pnpm patch`](https://pnpm.io/cli/patch), creating this diff to empty the definitions in `@types/testing-library__jest-dom/index.d.ts`:

```diff
diff --git a/index.d.ts b/index.d.ts
index 43ba6b7fe458e77d152fe0b2f7afeac05d8fc563..dfa540aa7d1ab8c78c31104d3210eee3c33a94c0 100755
--- a/index.d.ts
+++ b/index.d.ts
@@ -7,12 +7,9 @@
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 // Minimum TypeScript Version: 4.3
 
-/// <reference types="jest" />
+// NOTE: these definitions are left blank, to support using Testing Library Jest matchers with
+// Vitest, without having to use Jest's global types (for `expect`, etc).
 
-import { TestingLibraryMatchers } from './matchers';
+// Vitest's `expect` type is instead extended in `src/setupTests.ts`.
 
-declare global {
-    namespace jest {
-        interface Matchers<R = void, T = {}> extends TestingLibraryMatchers<typeof expect.stringContaining, R> {}
-    }
-}
+// For more context, see https://github.com/testing-library/jest-dom/issues/427
```

In `patches/@types__testing-library__jest-dom@5.14.5.patch`, with this in `package.json`:

```
"pnpm": {
  "patchedDependencies": {
    "@types/testing-library__jest-dom@5.14.5": "patches/@types__testing-library__jest-dom@5.14.5.patch"
  }
}
```

Paired with this in my Vitest setup file: https://github.com/testing-library/jest-dom/issues/439#issuecomment-1087504347

```ts
import matchers, {
  TestingLibraryMatchers,
} from '@testing-library/jest-dom/matchers';

declare global {
  namespace Vi {
    interface JestAssertion<T = any>
      extends jest.Matchers<void, T>,
        TestingLibraryMatchers<T, void> {}
  }
}

expect.extend(matchers);
```

**Comment by haikyuu** [comment]
nothing worked in my case :/

**Comment by mmiszy** [comment]
Solution for `pnpm` users:

Add this to your `package.json`:

```json
  "pnpm": {
    "patchedDependencies": {
      "@types/testing-library__jest-dom@5.14.5": "patches/@types__testing-library__jest-dom@5.14.5.patch"
    }
  }
```

Now, create a file `patches/@types__testing-library__jest-dom@5.14.5.patch` with the following contents:

```diff
diff --git a/index.d.ts b/index.d.ts
index 43ba6b7fe458e77d152fe0b2f7afeac05d8fc563..3bf91587abf21f15ac166bcae1f5a59b23884b87 100755
--- a/index.d.ts
+++ b/index.d.ts
@@ -7,7 +7,7 @@
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 // Minimum TypeScript Version: 4.3
 
-/// <reference types="jest" />
+// See https://github.com/testing-library/jest-dom/issues/427 for reference
 
 import { TestingLibraryMatchers } from './matchers';
```

Save both and run `pnpm i`.

**Comment by edufarre** [comment]
Do you have any updates on the status of this issue?
For now, the approach I've followed is the one mentioned into [another issue](https://github.com/testing-library/jest-dom/issues/439#issuecomment-1536524120) (which targets the latest version of Vite)

**Comment by madmadi** [comment]
Another solution if you don't mind to install a new package is to install [vitest-dom](https://github.com/chaance/vitest-dom). no hack or workaround and it works straightforward with pnpm too.

**Comment by merlinstardust** [comment]
I'm also seeing this issue on a brand new project

https://github.com/merlinstardust/coverage-zero-vitest-example/actions/runs/5384546869/jobs/9772635711#step:7:20
