### ISSUE TITLE
Deprecated source-map-resolve@0.6.0

### ISSUE THREAD

**Issue by mwallace72** [testing-library/jest-dom#435]
- `@testing-library/jest-dom` version: 5.15.1
- `node` version: 16.14.0
- `npm` (or `yarn`) version: 8.3.1

### What you did:

Installing v5.15.1 or v5.16.2

### What happened:

```npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated```

### Problem description:

No available newer module of https://www.npmjs.com/package/css that uses non-deprecated library

**Comment by JJ** [comment]
`css` is only used here, in this single function:

https://github.com/testing-library/jest-dom/blob/4cb606cc591345a2f44240d7e74740b26fa9fa85/src/utils.js#L103

There are other alternatives for obtaining the AST of a CSS declaration. However, they are not plug-in compatible, so changing it would require a certain amount of refactoring.

**Comment by gnapse** [comment]
This seems related to #443, which attempts to remove the dependency on this external `css` package.

**Comment by grosch** [comment]
Any updates on resolving this?

**Comment by octionut** [comment]
I'd like to have some updates on this as well

**Comment by MichaelDeBoey** [comment]
Fixed by #470
