### ISSUE TITLE
Export Vitest extend-expect

### ISSUE THREAD

**Issue by AndrewLeedham** [testing-library/jest-dom#439]
### Describe the feature you'd like:

I would like to use `jest-dom` in [Vitest](https://vitest.dev/).

### Suggested implementation:

Since both Jest and Vitest use the same style of matchers, and have very similiar APIs, perhaps `jest-dom` can export a secondary entry point for Vitest, or make the matchers export a first-class API.

### Describe alternatives you've considered:

I can manually add the matchers in a setup file using:
```javascript
import { expect } from 'vitest';
import * as matchers from '@testing-library/jest-dom/dist/matchers';

expect.extend(matchers);
```
However, I am reaching into the `dist` folder which is not a public API, also I am using TypeScript and having to setup the types myself, rather than using `@types/jest-dom`.

### Teachability, Documentation, Adoption, Migration Strategy:

This would just be an additional entry file just for Vitest, so should not change the functionality of `jest-dom`.

**Comment by gnapse** [comment]
I suspect that you can already do this (the same as above, but without the `/dist` part):

```js
import { expect } from 'vitest';
import * as matchers from '@testing-library/jest-dom/matchers';

expect.extend(matchers);
```

Can you confirm? I tried it myself, and it worked, but it would not hurt to make sure.

However, the types part is not solved. But that requires a PR to https://github.com/DefinitelyTyped/DefinitelyTyped. It'd be great if you'd contribute that for us. Can you?

**Comment by AndrewLeedham** [comment]
@gnapse Ah yes I missed that file. Although because of the CJS default export, it only works as 
```javascript
import matchers from '@testing-library/jest-dom/matchers';
```
But that is fine. I'll put a PR into DefinitelyTyped

**Comment by gnapse** [comment]
We're introducing EMS exports soon (#438). Does that help?

**Comment by AndrewLeedham** [comment]
@gnapse ESM exports will be great. Will probably involve reworking the `@types` package again. But for now I have added the matchers declaration: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59030

**Comment by IanVS** [comment]
>Will probably involve reworking the @types package again

Just curious, why is that?  I'm definitely open to suggestions on the ESM PR to avoid as much churn as possible.

**Comment by AndrewLeedham** [comment]
Was thinking it would need something like this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/57195 but could be wrong.

**Comment by hornta** [comment]
@AndrewLeedham Did you solve your problem? I think I'm in a similar sitation as you needing to use jest-dom in vitest. My "problem" was that when I installed jest-dom and imported it in my test setup file, typescript received all of jests types. This is causing a huge pain when I'm trying to refactor from Jest -> vitest.

I tried to import only the matchers and extended expect with those, as well as including the jest-dom type declaration matchers file in my tsconfig.json but now I'm unable to get typescript to see the jest-dom matchers.

**Comment by AndrewLeedham** [comment]
Hi @hornta. My Definitely Typed PR landed so you should be able to do this:

```typescript
// vitest-setup.ts
import { vi } from 'vitest';
import matchers, {
  TestingLibraryMatchers,
} from '@testing-library/jest-dom/matchers';

declare global {
  namespace Vi {
    interface JestAssertion<T = any>
      extends jest.Matchers<void, T>,
        TestingLibraryMatchers<T, void> {}
  }
}

expect.extend(matchers);
```

**Comment by kedar-s** [comment]
@AndrewLeedham Tried to use your exact same solution but I always end up with weird type errors

```ts
// vitest-setup.ts
import { vi } from 'vitest';
import matchers, {
  TestingLibraryMatchers,
} from '@testing-library/jest-dom/matchers';

declare global {
  namespace Vi {
    interface JestAssertion<T = any>
      extends jest.Matchers<void, T>,
        TestingLibraryMatchers<T, void> {}
  }
}

expect.extend(matchers);
```

```
Generic type 'Matchers<R, T, _R, _T>' requires between 3 and 4 type arguments.ts(2707)
```

I can see that the interface `Matchers` only takes 2 type arguments. 
```ts
interface Matchers<R = void, T = {}>
```

I'd appreciate any ideas on how to approach this problem.
Thanks!

**Comment by paulcwatts** [comment]
For those coming here after updating to vitest >= 0.31.0, the [above workaround](https://github.com/testing-library/jest-dom/issues/439#issuecomment-1087504347) no longer works because the assertions package location changed (https://github.com/vitest-dev/vitest/releases/tag/v0.31.0)

The following works for me:
```typescript
// vitest-setup.ts
import type { TestingLibraryMatchers } from "@testing-library/jest-dom/matchers";
import matchers from "@testing-library/jest-dom/matchers";
import { expect } from "vitest";

declare module "vitest" {
  interface Assertion<T = any>
    extends jest.Matchers<void, T>,
      TestingLibraryMatchers<T, void> {}
}

expect.extend(matchers);
```

**Comment by remy90** [comment]
I'm still getting the following error: 

> Error: Missing "./extend-expect" specifier in "@testing-library/jest-dom" package
 ❯ e node_modules/vite/dist/node/chunks/dep-df561101.js:21420:25
 ❯ n node_modules/vite/dist/node/chunks/dep-df561101.js:21420:627
 ❯ o node_modules/vite/dist/node/chunks/dep-df561101.js:21420:1297
 ❯ resolveExportsOrImports node_modules/vite/dist/node/chunks/dep-df561101.js:28712:20
 ❯ resolveDeepImport node_modules/vite/dist/node/chunks/dep-df561101.js:28731:31
 ❯ tryNodeResolve node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20
 ❯ Context.resolveId node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64
 ❯ TransformContext.resolve node_modules/vite/dist/node/chunks/dep-df561101.js:43923:23
 
 versions:
"vitest": "^0.34.3",
"@testing-library/jest-dom": "^6.1.2",
"@testing-library/react": "^14.0.0",

package manager: yarn 1.22.19
node: 18.16.1

What I've tried:

import '@testing-library/jest-dom'
import '@testing-library/jest-dom/extend-expect'
import matchers, { TestingLibraryMatchers } from '@testing-library/jest-dom/matchers'
import { afterEach, beforeEach, expect, vi } from 'vitest'

declare module 'vitest' {
  interface Assertion<T = any> extends jest.Matchers<void, T>, TestingLibraryMatchers<T, void> {}
}

expect.extend(matchers)

**Comment by macmillan78** [comment]
@remy90 Just ran into the same problem. importing with `import * as matchers from '@testing-library/jest-dom/matchers'` works for me. Could you confirm?

**Comment by IanVS** [comment]
`extend-expect` was removed in the latest breaking change, and the solution from @macmillan78 is the correct approach.

**Comment by IanVS** [comment]
For vitest, you can also follow the steps in the readme: https://github.com/testing-library/jest-dom#with-vitest

**Comment by simonrevill** [comment]
For me, this worked and I didn't need to declare the types:

```typescript
// vite.config.ts
/// <reference types="vitest" />
/// <reference types="vite/client" />

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./setupTests.ts"],
    css: true,
  },
});
```

```typescript
// setupTests.ts
import "@testing-library/jest-dom/vitest";
```

**Comment by IanVS** [comment]
@bradleyball please open a new issue with all the details of the problem you're having.

**Comment by mibcadet** [comment]
for me nearly all worked but IDE couldnt see those matchers types, this was solution I used to have no TS issues:
[https://github.com/testing-library/jest-dom/pull/624](https://github.com/testing-library/jest-dom/pull/624)
