### ISSUE TITLE
toBeChecked does not match aria-checked

### ISSUE THREAD

**Issue by viQcinese** [testing-library/jest-dom#464]
- `@testing-library/jest-dom` version: 4.0.0
- `node` version: 16.14.0
- `yarn` version: 1.22.19

### Summary
I have a checkbox which I test using `toBeChecked`, and it work as expected, both for checked and not checked states. But as I read `js-dom` implementation, I understood that this assertion is controlled by `aria-checked` property. I tried accessing this property, and it returned null, while the assertion is working as expected. Can anyone explain to me why this happens?

### Relevant code or config:
```jsx
import { Checkbox } from '@chakra-ui/react';
...
<Checkbox>All</Checkbox>
```

### What you did:

```js
const allCheckbox = screen.getByRole('checkbox', { checked: true })

console.log(allCheckbox.ariaChecked)

expect(allCheckbox).toBeChecked()
```

### What happened:

Assertion passed, stating that the checkbox is indeed checked, as it was. But console logged `null`, stating that `aria-checked` attribute is unset, as it is. How can it be that both results differ?

**Comment by AndersonSMed** [comment]
What happens is that your lib is rendering a native HTML checkbox under the hood, and they don't need to have an `aria-checked` attribute in order to be viewed as checked, [as you can see here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox).

**Comment by viQcinese** [comment]
> What happens is that the `Checkbox` component renders a native checkbox element. Native checkboxes doesn't need to have an `aria-checked` attribute to be viewed as checked, once they already have the `checked` and `value` attributes [as you can see here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox).

I understand that. But the [js-dom implementation](https://github.com/testing-library/jest-dom/blob/main/src/to-be-checked.js#L31) doesn't make that difference. It checks specifically for `aria-checked`, which evaluates to null, even though the checkbox is checked.
