### ISSUE TITLE
@types/testing-library__jest-dom is not available for node12

### ISSUE THREAD

**Issue by AWITW** [testing-library/jest-dom#473]
- `@testing-library/jest-dom` version:
- `node` : 12
- `yarn` version: 1.22.17

### Problem description:
error expect@29.0.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.10"

**Comment by nickmccurdy** [comment]
I don't think we can control the compatibility of `@types/testing-library__jest-dom` because it's maintained by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Node 12 is still unsupported though, so I'd recommend you upgrade to Node 14.

**Comment by jinlong** [comment]
@types/testing-library__jest-dom contains `{ @types/jest: "*" }` dependency，due to jest release v29.0 recently，our app may auto install latest version, jest@29 is not available for node12. 

Could you change the ‘*’ wildcard version to particular version?

**Comment by nickmccurdy** [comment]
As I said, we don't control that. You can open an issue with DefinitelyTyped if you want, though I doubt it will be solved because Node 12 is no longer supported. If you can't upgrade yet, disable engine checks or use a lockfile (at your own risk).
