### ISSUE TITLE
Update dependency dom-accessibility-api

### ISSUE THREAD

**Issue by anfavretto** [testing-library/jest-dom#487]
### Describe the feature you'd like:

jest-dom has the dependency dom-accessibility-api where was found one Circular Dependency. It was fixed on version v0.5.12. The current version of jest-dom is using "dom-accessibility-api": "^0.5.6"

### Suggested implementation:

Upgrade this dependency.

**Comment by amanmahajan7** [comment]
The latest version of `dom-accessibility-api` also supports `aria-description` and it would be great if we can update the dependency.
