### ISSUE TITLE
6.1.0 failing on "Cannot find module '@testing-library/jest-dom'"

### ISSUE THREAD

**Issue by andrewbusch7** [testing-library/jest-dom#522]
- `@testing-library/jest-dom` version: 6.1.0
- `node` version: v18.13.0
- `npm` version: 8.19.3

### Relevant code or config:

File src/setupTests.js
```js
import "@testing-library/jest-dom";
```

### What you did:

I upgraded from 6.0.1 to 6.1.0. Rollback to 6.0.1 fixes it.

### What happened:

`npm run tests` now returns a failure on every test:

```
Cannot find module '@testing-library/jest-dom' from 'src/setupTests.js' for every test run
```

### Reproduction:

If the root cause isn't obvious, I can work on a repo with a replicable example.

### Problem description:

Fails always on current version.

### Suggested solution:

My guess is something in https://github.com/testing-library/jest-dom/commit/61d17bd15b7d2cecb2868a2befe563cb9d5e22cf broke things.

**Comment by CrOrc** [comment]
In package.json
there a lines
```
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
```
These files are not in package

**Comment by SteKoe** [comment]
I have fixed this in PR #523

**Comment by meza** [comment]
There's a great package: https://publint.dev/ that can lint the package json for proper hybrid settings!
Might be worth adding it to them mix

**Comment by crs1138** [comment]
I believe the problem is actually with the new version of the @adobe/css-tools package. I've submitted a PR with them: https://github.com/adobe/css-tools/pull/183

**Comment by nickmccurdy** [comment]
Can someone who's had this issue please verify if it's working or still erroring with jest-dom 6.1.2? We've fixed all our ESM publishing issues as far as I'm aware, so it could be https://github.com/adobe/css-tools/pull/183.

**Comment by andresmoschini** [comment]
> Can someone who's had this issue please verify if it's working or still erroring with jest-dom 6.1.2? We've fixed all our ESM publishing issues as far as I'm aware, so it could be [adobe/css-tools#183](https://github.com/adobe/css-tools/pull/183).

It was fixed in my project: https://github.com/FromDoppler/doppler-editors-webapp/pull/690

**Comment by andrewbusch7** [comment]
Yep working for me too, thanks all!

**Comment by crs1138** [comment]
> Can someone who's had this issue please verify if it's working or still erroring with jest-dom 6.1.2? We've fixed all our ESM publishing issues as far as I'm aware, so it could be [adobe/css-tools#183](https://github.com/adobe/css-tools/pull/183).

The v6.1.2 fixed it for me.
