### ISSUE TITLE
toHaveStyle fails on custom property names containing uppercase letters

### ISSUE THREAD

**Issue by depoulo** [testing-library/jest-dom#551]
The error will be the dreaded _Compared values have no visual difference._

### Relevant code or config:

It's easy to reproduce by changing the existing test:

https://github.com/testing-library/jest-dom/blob/4ae0231be83f3ca79ae3ff735cf6c0ceb399fea4/src/__tests__/to-have-style.js#L122-L128

```js
  test('handles inline custom properties', () => {
    const {queryByTestId} = render(`
      <span data-testid="color-example" style="--backgroundColor: blue">Hello World</span>
    `)
    expect(queryByTestId('color-example')).toHaveStyle('--backgroundColor: blue') // this will fail
  })
```

The culprit is the `.toLowerCase()` here:

https://github.com/testing-library/jest-dom/blob/4ae0231be83f3ca79ae3ff735cf6c0ceb399fea4/src/to-have-style.js#L23

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#sect2):

> **Note**: Custom property names are case sensitive — `--my-color` will be treated as a separate custom property to `--My-color`.

Current workarounds are changing the code under test, including the stylesheets, to use all-lowercase custom property names, or to not use `.toHaveStyle()`.

**Comment by gnapse** [comment]
Thanks for reporting this bug.

BTW, would you be open to contribute to fix it yourself?

**Comment by depoulo** [comment]
Yes, sure!

**Comment by depoulo** [comment]
There we go: #552
