### ISSUE TITLE
.toHaveAttribute('disabled') and .toBeDisabled()

### ISSUE THREAD

**Issue by haroldmud** [testing-library/jest-dom#560]
### Discussed in https://github.com/testing-library/jest-dom/discussions/325

<div type='discussions-op-text'>

<sup>Originally posted by **StefanZivkovic** December 30, 2020</sup>
I am using Button from @material-ui/core, and my test have different output depending of which assert method I use. Initially button is disabled when page loads, and in snapshot there is confirmation about it.
```
<button
              className="MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-containedSizeLarge MuiButton-sizeLarge Mui-disabled Mui-disabled"
              disabled={true}
              onBlur={[Function]}
              ...
              tabIndex={-1}
              type="button"
            >
              <span
                className="MuiButton-label"
              >
                w4pay.termsOfElectronicPay.buttonText
```
Scenarios:
**expect(readyToEsignButton).not.toBeDisabled();** - FAILS (expected)
**expect(readyToEsignButton).toBeDisabled();** - PASSES (expected)
**expect(readyToEsignButton).toHaveAttribute('disabled');** - PASSES (not sure what to expect here since value is not provided as second attribute)
**expect(readyToEsignButton).toHaveAttribute('disabled', 'true');** - FAILS 
```
Expected the element to have attribute:
      disabled="true"
    Received:
      disabled=""
```
Mostly i am confused with last output, because disable="" even though it is disabled (i would expect to have value of true).

Any thoughts? </div>

**Comment by gnapse** [comment]
> Mostly i am confused with last output, because disable="" even though it is disabled (i would expect to have value of true).

The answer is already in the very discussion thread that you linked to: https://github.com/testing-library/jest-dom/discussions/325

Check in particular [this comment](https://github.com/testing-library/jest-dom/discussions/325#discussioncomment-253661). Please, continue the discussion over there if you have any more questions.
