### ISSUE TITLE
support for asymmetricMatch as the value for toHaveAttribute matcher

### ISSUE THREAD

**Issue by revathskumar** [testing-library/jest-dom#91]
### Describe the feature you'd like:

Adding support for [asymmetricMatchers](https://github.com/facebook/jest/blob/151c961b13ca664e31fd52e87d9939e546ab46f3/packages/expect/src/asymmetricMatchers.ts) like [expec.stringContaining](https://jestjs.io/docs/en/expect#expectstringcontainingstring) as the value to `toHaveAttribute` matcher
Eg: 
```js

      expect(getByLabelText(/Download Template/)).toHaveAttribute(
        "href",
        expect.stringContaining("?type=instruments")
      );

```

### Describe alternatives you've considered:

As of now this is achived by 

```js

      expect(getByLabelText(/Download Template/).getAttribute("href")).toEqual(
        expect.stringContaining("type=instruments")
      );

```

**Comment by gnapse** [comment]
I'm new to this asymmetric matchers thing. Thanks for bringing this up.

A couple of questions:

* What's the difference with enabling `toHaveAttribute` to receive a regex as the second argument? For example `expect(element).toHaveAttribute('href', /type=instruments/)`.
* Wouldn't it be better if we decide to do this, to try to see if other matchers in this library can benefit from supporting these asymmetric matchers?

Also, I'm not sure I'll have time to tackle this if we accept supporting it. Would you be able to do it if so?

**Comment by revathskumar** [comment]
@gnapse Thanks for quick reply

I personally prefer `asymmetricMatch` to simple regex, 
* to keep the api compatible with other `expect` matchers.
* dont want to complicate things by writing regexp instead of simple string
* negative lookup regex are nightmare, instead we can use `expect.not.stringMatching()`
* can use other methods like `expect.anything()`, `expect.not.stringContaining()`, `expect.not.stringMatching()`   

expect support for `Regex` via [expect.stringMatching](https://jestjs.io/docs/en/expect.html#expectstringmatchingstring-regexp). 

I will give a try to add this during the weekend.

**Comment by gnapse** [comment]
Sounds good, that's quite a list of advantages you got there! Yes, please. I'm looking forward to learn how this works by seeing how you make it work with our matchers. Thanks!

PS: One thing I anticipate will need our attention at some point is TypeScript. The second argument to `toHaveAttribute` is now typed as `string`, and we'll need to be

```typescript
string | WhateverTypeAsymmetricMatchersReturn
```
